export type ImportedCommercialAccount = {
  id: string;
  name: string;
  city: string | null;
  pricing_model: string | null;
  cleaner_name: string | null;
  hours: number | string | null;
  frequency: string | null;
  revenue: number | null;
  cost: number | null;
  rate_per_service?: number | null;
  cleaner_flat_rate?: number | null;
  payment_method: string | null;
  contract_start: string | null;
  contract_end: string | null;
  last_contact_date: string | null;
  last_qcc_date: string | null;
  has_supplies: boolean;
  has_keys: boolean;
  supply_delivery_date: string | null;
  estimated_fill_date: string | null;
  supplies_notes: string | null;
  source_sheet: string;
  schedule_rules?: ImportedCommercialScheduleRule[];
};

export type ImportedCommercialScheduleRule = {
  day_of_week: number;
  paid_hours: number;
  assigned_cleaner_name?: string | null;
  active?: boolean;
  frequency_type?: "monthly" | "weekly" | "custom" | "biweekly" | "every_3_weeks" | "every_15_days" | null;
  frequency_interval?: number | null;
  anchor_date?: string | null;
  notes?: string | null;
  effective_start_date?: string | null;
  effective_end_date?: string | null;
  effective_from?: string | null;
  effective_until?: string | null;
};

export const importedCommercialAccounts: ImportedCommercialAccount[] = [
  {
    id: "import-13demarzo-irvine-31",
    name: "13demarzo",
    city: "Irvine",
    pricing_model: "flat rate",
    cleaner_name: "Sandra Hernandez",
    hours: 2.5,
    frequency: "2x per week",
    revenue: 950,
    cost: 499,
    rate_per_service: 57.5,
    payment_method: "Credit Card",
    contract_start: "2026-02-08",
    contract_end: "2027-02-02",
    last_contact_date: "2026-02-18",
    last_qcc_date: "2026-04-14",
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "Dumpster in front of the building to the right of Capital Seafood Restaurant. Park vehicle in the main parking lot. Take special emphasis on all surfaces.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 1, paid_hours: 2.5, assigned_cleaner_name: "Sandra Hernandez", notes: "Monday 9:00 PM - 10:00 PM" },
      { day_of_week: 4, paid_hours: 2.5, assigned_cleaner_name: "Sandra Hernandez", notes: "Thursday 9:00 PM - 10:00 PM" },
    ]
  },
  {
    id: "import-cornerstone-southern-california",
    name: "Cornerstone Rehab",
    city: "Santa Ana",
    pricing_model: "Flat Rate",
    cleaner_name: "Kassandra Valentin",
    hours: 7,
    frequency: "3x per week",
    revenue: 2850,
    cost: 1943.5,
    rate_per_service: 161,
    payment_method: "Credit Card",
    contract_start: "2026-08-16",
    contract_end: null,
    last_contact_date: null,
    last_qcc_date: null,
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "Alarm code 0505. Detailed dusting is super important. Multiple keys are given, one for office door, one for supply closet door. Restocking supplies is super important. Leave individual offices locked after cleaning.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 1, paid_hours: 7, assigned_cleaner_name: "Kassandra Valentin", notes: "Monday 5:00 PM - 5:00 AM" },
      { day_of_week: 3, paid_hours: 7, assigned_cleaner_name: "Kassandra Valentin", notes: "Wednesday 5:00 PM - 5:00 AM" },
      { day_of_week: 5, paid_hours: 7, assigned_cleaner_name: "Kassandra Valentin", notes: "Friday 5:00 PM - 5:00 AM" },
    ]
  },
  {
    id: "import-elevate-aerial-hb-huntington-beach-22",
    name: "Elevate Aerial Huntington Beach",
    city: "Huntington Beach",
    pricing_model: "Flat rate",
    cleaner_name: "Luz Uribe",
    hours: 6,
    frequency: "1x per week",
    revenue: 800,
    cost: 498,
    rate_per_service: 138,
    payment_method: "Check",
    contract_start: "2025-12-07",
    contract_end: null,
    last_contact_date: "2026-02-17",
    last_qcc_date: "2026-04-14",
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "Lockbox outside on the front door code 1379. Ensuring the door is always locked because its tricky. Never wearing shoes inside of the training room on the carpet, using a specific vacuum for that area. Flip mats and clean one side each week.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 0, paid_hours: 6, assigned_cleaner_name: "Luz Uribe", notes: "Sunday (Any time)" }
    ]
  },
  {
    id: "import-field-ai-irvine-30",
    name: "Field AI",
    city: "Irvine",
    pricing_model: "flat rate",
    cleaner_name: "Veronica Ladinos",
    hours: 6,
    frequency: "5x per week",
    revenue: 3390,
    cost: 2093,
    payment_method: "ACH",
    contract_start: "2026-01-13",
    contract_end: "2026-08-31",
    last_contact_date: "2026-02-18",
    last_qcc_date: "2026-04-14",
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "3 Morgan, Irvine. Monday through Friday Trash. Monday full office cleaning. Be sure all toilet paper dispensers have at least 1 FULL roll. Kitchen cleaning needs coffee machine detailed cleaning. Cuenta cancelada a partir del 31 de agosto de 2026.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 1, paid_hours: 6, assigned_cleaner_name: "Veronica Ladinos", effective_until: "2026-08-31", notes: "Monday 11:58 PM - 4:00 AM" },
      { day_of_week: 2, paid_hours: 6, assigned_cleaner_name: "Veronica Ladinos", effective_until: "2026-08-31", notes: "Tuesday 11:58 PM - 4:00 AM" },
      { day_of_week: 3, paid_hours: 6, assigned_cleaner_name: "Veronica Ladinos", effective_until: "2026-08-31", notes: "Wednesday 11:58 PM - 4:00 AM" },
      { day_of_week: 4, paid_hours: 6, assigned_cleaner_name: "Veronica Ladinos", effective_until: "2026-08-31", notes: "Thursday 11:58 PM - 4:00 AM" },
      { day_of_week: 5, paid_hours: 6, assigned_cleaner_name: "Veronica Ladinos", effective_until: "2026-08-31", notes: "Friday 11:58 PM - 4:00 AM" },
    ]
  },
  {
    id: "import-globar-medspa-costa-mesa-35",
    name: "GLO Bar MedSpa",
    city: "Costa Mesa",
    pricing_model: "flat rate",
    cleaner_name: "Juan Romero",
    hours: 3,
    frequency: "2x per week",
    revenue: 1450,
    cost: 468,
    rate_per_service: 69,
    payment_method: "Zelle",
    contract_start: "2026-02-23",
    contract_end: "2027-02-23",
    last_contact_date: "2026-02-23",
    last_qcc_date: null,
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "Door code: 5436. Alarm code: 2891. Internal: Details around staff kitchen and baseboards, chair details in all operatory rooms. Key is given and dumpster is outside the back door to the right.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 0, paid_hours: 3, assigned_cleaner_name: "Juan Romero", notes: "Sunday 6:00 PM - 9:00 AM" },
      { day_of_week: 3, paid_hours: 3, assigned_cleaner_name: "Juan Romero", notes: "Wednesday 6:00 PM - 9:00 AM" },
    ]
  },
  {
    id: "import-green-leaf-botanicals-whittier-8",
    name: "Green Leaf Botanicals",
    city: "Whittier",
    pricing_model: "per Service",
    cleaner_name: "Lorena Benitez",
    hours: 2,
    frequency: "Monthly",
    revenue: 238,
    cost: 119,
    rate_per_service: 119,
    payment_method: "Credit Card",
    contract_start: "2026-01-26",
    contract_end: null,
    last_contact_date: "2026-02-09",
    last_qcc_date: "2026-04-14",
    has_supplies: false,
    has_keys: false,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "Monthly service. Cleaner: Lorena Benitez (100% residencial - non-hourly). Facturada comercialmente pero operada en Booking Koala.",
    source_sheet: "Accounts",
    schedule_rules: []
  },
  {
    id: "import-ilg-corona-office-corona-19",
    name: "ILG Corona Office",
    city: "Corona",
    pricing_model: "Flat rate",
    cleaner_name: "Sandra Hernandez",
    hours: 3,
    frequency: "3x per week",
    revenue: 1163,
    cost: 897,
    rate_per_service: 69,
    payment_method: "Check",
    contract_start: "2025-11-22",
    contract_end: null,
    last_contact_date: "2026-02-18",
    last_qcc_date: "2026-04-14",
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "507 Queensland Circle, Corona. Alarm OFF: 49001 (OFF). TO SET: 49002 (AWAY). DO NOT PRESS 3 (STAY BUTTON). Constant beeping: press silence 2 times on gray system. Call Jake with questions.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 1, paid_hours: 3, assigned_cleaner_name: "Sandra Hernandez", notes: "Monday 5:00 PM - 2:00 AM" },
      { day_of_week: 3, paid_hours: 3, assigned_cleaner_name: "Sandra Hernandez", notes: "Wednesday 5:00 PM - 2:00 AM" },
      { day_of_week: 5, paid_hours: 3, assigned_cleaner_name: "Sandra Hernandez", notes: "Friday 5:00 PM - 2:00 AM" },
    ]
  },
  {
    id: "import-ilg-irvine-office-irvine-18",
    name: "ILG Irvine Office",
    city: "Irvine",
    pricing_model: "Flat rate",
    cleaner_name: "Maria Lopez",
    hours: 2.5,
    frequency: "3x per week",
    revenue: 1800,
    cost: 1196,
    rate_per_service: 92,
    payment_method: "Check",
    contract_start: "2025-11-19",
    contract_end: null,
    last_contact_date: "2026-02-18",
    last_qcc_date: "2026-04-14",
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "75 Doppler, Irvine. Budget: 2 hrs 30 min. Use keys to clean Suite 100. Details on front surface door are important. No bathroom or outside hallway cleaning needed. Two different keys.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 1, paid_hours: 2.5, assigned_cleaner_name: "Maria Lopez", notes: "Monday 5:00 PM - 11:00 PM" },
      { day_of_week: 3, paid_hours: 2.5, assigned_cleaner_name: "Maria Lopez", notes: "Wednesday 5:00 PM - 11:00 PM" },
      { day_of_week: 5, paid_hours: 2.5, assigned_cleaner_name: "Maria Lopez", notes: "Friday 5:00 PM - 11:00 PM" },
    ]
  },
  {
    id: "import-ilg-valencia-office-valencia-21",
    name: "Interior Logic Group - Valencia Office",
    city: "Valencia",
    pricing_model: "Flat rate",
    cleaner_name: "Emmi Guerra",
    hours: 5.5,
    frequency: "3x per week",
    revenue: 1890,
    cost: 1345.5,
    rate_per_service: 103.5,
    payment_method: "Check",
    contract_start: "2026-01-27",
    contract_end: null,
    last_contact_date: "2026-02-18",
    last_qcc_date: "2026-04-14",
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "27229 Turnberry Lane, Valencia. Lockbox on gas meter to left of front entrance code 8008. Keep supply closet door cracked. Upstairs offices 2x per month, trash every service. Warehouse restroom needs cleaning.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 1, paid_hours: 5.5, assigned_cleaner_name: "Emmi Guerra", notes: "Monday 5:00 PM - 5:00 AM" },
      { day_of_week: 3, paid_hours: 5.5, assigned_cleaner_name: "Emmi Guerra", notes: "Wednesday 5:00 PM - 5:00 AM" },
      { day_of_week: 5, paid_hours: 5.5, assigned_cleaner_name: "Emmi Guerra", notes: "Friday 5:00 PM - 5:00 AM" },
    ]
  },
  {
    id: "import-ilg-westlake-westlake-village-20",
    name: "ILG Westlake",
    city: "Westlake Village",
    pricing_model: "Flat rate",
    cleaner_name: "Emmi Guerra",
    hours: 2.5,
    frequency: "3x per week",
    revenue: 1130,
    cost: 747.5,
    rate_per_service: 57.5,
    payment_method: "Check",
    contract_start: "2025-11-20",
    contract_end: null,
    last_contact_date: "2026-02-18",
    last_qcc_date: "2026-04-14",
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "Westlake office cleaning.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 1, paid_hours: 2.5, assigned_cleaner_name: "Emmi Guerra", notes: "Monday 5:00 PM - 5:00 AM" },
      { day_of_week: 3, paid_hours: 2.5, assigned_cleaner_name: "Emmi Guerra", notes: "Wednesday 5:00 PM - 5:00 AM" },
      { day_of_week: 5, paid_hours: 2.5, assigned_cleaner_name: "Emmi Guerra", notes: "Friday 5:00 PM - 5:00 AM" },
    ]
  },
  {
    id: "import-kott-koatings-lake-forest-13",
    name: "Kott Koatings",
    city: "Lake Forest",
    pricing_model: "per Service",
    cleaner_name: "Unassigned",
    hours: 3,
    frequency: "1x per week",
    revenue: 606.67,
    cost: 299,
    rate_per_service: 69,
    payment_method: "Check",
    contract_start: "2025-12-09",
    contract_end: null,
    last_contact_date: "2026-02-10",
    last_qcc_date: "2026-04-14",
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "Clean front lobby, 2 bathrooms, offices left and right of lobby. Alfredo will allow in.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 3, paid_hours: 3, assigned_cleaner_name: "Unassigned", notes: "Wednesday 9:00 AM - 12:00 PM" }
    ]
  },
  {
    id: "import-kush-fine-art-laguna-beach-14",
    name: "Kush Fine Art",
    city: "Laguna Beach",
    pricing_model: "per Service",
    cleaner_name: "Ana Morales",
    hours: 3,
    frequency: "Every 21 days",
    revenue: 340,
    cost: 95.31,
    rate_per_service: 69,
    payment_method: "Credit Card",
    contract_start: "2025-12-22",
    contract_end: null,
    last_contact_date: "2026-02-18",
    last_qcc_date: "2026-04-14",
    has_supplies: false,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "Detailed dusting not touching sculptures. Cobweb cleaning a must. Parking near library.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 1, paid_hours: 3, assigned_cleaner_name: "Sandra Hernandez", frequency_type: "every_3_weeks", anchor_date: "2025-12-22", notes: "Every 3 weeks" }
    ]
  },
  {
    id: "import-lsg-sky-chefs-costa-mesa",
    name: "LSG Sky Chefs",
    city: "Costa Mesa",
    pricing_model: "Flat Rate",
    cleaner_name: "Luz and Vanessa",
    hours: 10,
    frequency: "7x per week",
    revenue: 10750,
    cost: 7495,
    rate_per_service: 230,
    payment_method: "ACH",
    contract_start: "2026-07-09",
    contract_end: null,
    last_contact_date: null,
    last_qcc_date: null,
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "Maria Mejia (Sun, Mon, Wed, Thu) & Luz Uribe (Tue, Fri, Sat). 10 hrs per service.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 0, paid_hours: 10, assigned_cleaner_name: "Maria Mejia", notes: "Sunday 10h" },
      { day_of_week: 1, paid_hours: 10, assigned_cleaner_name: "Maria Mejia", notes: "Monday 10h" },
      { day_of_week: 2, paid_hours: 10, assigned_cleaner_name: "Luz Uribe", notes: "Tuesday 10h" },
      { day_of_week: 3, paid_hours: 10, assigned_cleaner_name: "Maria Mejia", notes: "Wednesday 10h" },
      { day_of_week: 4, paid_hours: 10, assigned_cleaner_name: "Maria Mejia", notes: "Thursday 10h" },
      { day_of_week: 5, paid_hours: 10, assigned_cleaner_name: "Luz Uribe", notes: "Friday 10h" },
      { day_of_week: 6, paid_hours: 10, assigned_cleaner_name: "Luz Uribe", notes: "Saturday 10h" },
    ]
  },
  {
    id: "import-macarthur-dental-arts-irvine-37",
    name: "MacArthur Dental Arts",
    city: "Irvine",
    pricing_model: "Flat Rate",
    cleaner_name: "Kassandra Valentin",
    hours: 1.5,
    frequency: "4x per week",
    revenue: 1060,
    cost: 746.92,
    payment_method: "Credit card",
    contract_start: "2026-03-01",
    contract_end: null,
    last_contact_date: null,
    last_qcc_date: null,
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "Alarm code: TO ARM: 7897 ARM, TO DISARM: 7897 DISARM. Lockbox code: 8544. Dumpster on right side of parking lot. Mon-Wed light cleaning and trash, Thu floor mopping.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 1, paid_hours: 1.5, assigned_cleaner_name: "Kassandra Valentin", notes: "Monday" },
      { day_of_week: 2, paid_hours: 1.5, assigned_cleaner_name: "Kassandra Valentin", notes: "Tuesday" },
      { day_of_week: 3, paid_hours: 1.5, assigned_cleaner_name: "Kassandra Valentin", notes: "Wednesday" },
      { day_of_week: 4, paid_hours: 1.5, assigned_cleaner_name: "Kassandra Valentin", notes: "Thursday" },
    ]
  },
  {
    id: "import-mama-s-restaurant-huntington-beach-3",
    name: "Mama's Restaurant Huntington Beach",
    city: "Huntington Beach",
    pricing_model: "Per Service",
    cleaner_name: "Juan Romero",
    hours: 4,
    frequency: "Weekly (Fri)",
    revenue: 1898,
    cost: 902,
    rate_per_service: 200,
    payment_method: "Check",
    contract_start: "2024-04-01",
    contract_end: "2026-04-01",
    last_contact_date: "2026-02-18",
    last_qcc_date: "2026-04-14",
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "No alarm, team has keys. Bathrooms, kitchen floor. Rate per service: $200.00 to Juan Romero.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 5, paid_hours: 4, assigned_cleaner_name: "Juan Romero", notes: "Friday ($200 per service flat rate)" }
    ]
  },
  {
    id: "import-mama-s-restaurant-los-alamitos-4",
    name: "Mama's Restaurant Los Alamitos",
    city: "Los Alamitos",
    pricing_model: "Per Service",
    cleaner_name: "Juan Romero",
    hours: 4,
    frequency: "Weekly (Fri)",
    revenue: 2028,
    cost: 858,
    rate_per_service: 200,
    payment_method: "Check",
    contract_start: "2024-04-01",
    contract_end: "2026-04-01",
    last_contact_date: "2026-02-18",
    last_qcc_date: "2026-04-14",
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "Friday weekly service. $200 flat rate to Juan Romero.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 5, paid_hours: 4, assigned_cleaner_name: "Juan Romero", notes: "Friday ($200 per service flat rate)" }
    ]
  },
  {
    id: "import-miracle-minds-newport-32",
    name: "Miracle Minds (Miraculous Milestones)",
    city: "Newport",
    pricing_model: "flat rate",
    cleaner_name: "Luz Uribe",
    hours: 2.75,
    frequency: "3x per week",
    revenue: 1750,
    cost: 822.25,
    rate_per_service: 63.25,
    payment_method: "Credit Card",
    contract_start: "2026-02-18",
    contract_end: "2027-02-18",
    last_contact_date: "2026-02-18",
    last_qcc_date: "2026-04-14",
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "Address: 1000 Bison Avenue, Newport Beach. Visitor cards given to get in. Dumpster in parking lot. Liquids if needed in supply closet. Carpeted areas dont need cleaning. Cleaning of 4 classrooms and 2 restrooms in the classrooms. No community bathrooms or hallways needed. Schedule: Tue & Thu 5:30 PM, Fri 8:00 PM (Luz Uribe).",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 2, paid_hours: 2.75, assigned_cleaner_name: "Luz Uribe", notes: "Tuesday 5:30 PM" },
      { day_of_week: 4, paid_hours: 2.75, assigned_cleaner_name: "Luz Uribe", notes: "Thursday 5:30 PM" },
      { day_of_week: 5, paid_hours: 2.75, assigned_cleaner_name: "Luz Uribe", notes: "Friday 8:00 PM" },
    ]
  },
  {
    id: "import-miwa-office-irvine-27",
    name: "MIWA Lock CO., LTD.",
    city: "Irvine",
    pricing_model: "per Service",
    cleaner_name: "Unassigned",
    hours: 2,
    frequency: "1x per week",
    revenue: 480,
    cost: 239,
    rate_per_service: 46,
    payment_method: "ACH",
    contract_start: "2025-12-23",
    contract_end: null,
    last_contact_date: "2026-02-18",
    last_qcc_date: "2026-04-14",
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "9272 Jeronimo Road. Cleaning suites 119 and 112 at 3pm on Fridays. Contact Roy Mendiola.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 5, paid_hours: 2, assigned_cleaner_name: "Unassigned", notes: "Friday 3:00 PM - 6:00 PM" }
    ]
  },
  {
    id: "import-moxi3-costa-mesa",
    name: "MOXI3 Costa Mesa",
    city: "Costa Mesa",
    pricing_model: "Flat Rate",
    cleaner_name: "Luz Uribe",
    hours: 3.5,
    frequency: "3x per week",
    revenue: 1100,
    cost: 642,
    rate_per_service: 69,
    payment_method: "Credit card",
    contract_start: "2026-06-12",
    contract_end: null,
    last_contact_date: null,
    last_qcc_date: null,
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "Lockbox code 3400. Alarm code: 1480. Address: 1514 Newport Blvd, Costa Mesa. Dumpster around back of building. Ensure front and back doors are completely locked. Do not unplug sound system or gym cables. Saturday cleanings are only for training room, flooring and mirrors in training room. 1st and 3rd Saturday: steam clean pilates mats deep clean (+2h).",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 1, paid_hours: 3.5, assigned_cleaner_name: "Luz Uribe", notes: "Monday 9:00 PM" },
      { day_of_week: 4, paid_hours: 3.5, assigned_cleaner_name: "Luz Uribe", notes: "Thursday 9:00 PM" },
      { day_of_week: 6, paid_hours: 3.5, assigned_cleaner_name: "Luz Uribe", notes: "Saturday 9:00 PM (Training room, flooring & mirrors only. 1st & 3rd Sat: steam clean pilates mats +2h)" },
    ]
  },
  {
    id: "import-moxi3-dana-point",
    name: "MOXI3 Dana Point",
    city: "Dana Point",
    pricing_model: "Flat Rate",
    cleaner_name: "Ana Morales",
    hours: 3,
    frequency: "2x per week",
    revenue: 1000,
    cost: 642,
    rate_per_service: 69,
    payment_method: "Credit card",
    contract_start: "2026-06-12",
    contract_end: null,
    last_contact_date: null,
    last_qcc_date: null,
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "34137 Pacific Coast Highway. Lockbox code 5464. Alarm code: 1480.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 1, paid_hours: 3, assigned_cleaner_name: "Ana Morales", notes: "Monday 7:30 PM - 5:00 AM" },
      { day_of_week: 4, paid_hours: 3, assigned_cleaner_name: "Ana Morales", notes: "Thursday 7:30 PM - 5:00 AM" },
    ]
  },
  {
    id: "import-oc-spine-sports-physicians",
    name: "Orange County Spine and Sports Physicians",
    city: "Huntington Beach",
    pricing_model: "flat rate",
    cleaner_name: "Mirna Contreras",
    hours: 2.5,
    frequency: "2nd & 4th Sat of Month",
    revenue: 380,
    cost: 125,
    rate_per_service: 57.5,
    payment_method: "Credit Card",
    contract_start: "2026-01-31",
    contract_end: null,
    last_contact_date: "2026-02-18",
    last_qcc_date: "2026-04-14",
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "18800 Delaware Street. Suite 1000 on 10th floor. 9:00 AM - 11:20 AM.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 6, paid_hours: 2.5, assigned_cleaner_name: "Mirna Contreras", frequency_type: "monthly", anchor_date: "2026-08-08", notes: "2nd & 4th Sat of Month (9:00 AM - 11:20 AM)" }
    ]
  },
  {
    id: "import-posh-pooch-seal-beach-15",
    name: "Posh Pooch",
    city: "Seal Beach",
    pricing_model: "per Service",
    cleaner_name: "Luz Uribe",
    hours: 4,
    frequency: "Every month on 2nd Mon",
    revenue: 338,
    cost: 92,
    rate_per_service: 92,
    payment_method: "Credit Card",
    contract_start: "2025-12-08",
    contract_end: null,
    last_contact_date: "2026-02-18",
    last_qcc_date: "2026-04-14",
    has_supplies: false,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "350 Main Street. Time: 3:00 PM - 8:15 PM. 2nd Monday of month (Aug 10, Sep 14). Key given.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 1, paid_hours: 4, assigned_cleaner_name: "Luz Uribe", frequency_type: "monthly", anchor_date: "2026-08-10", notes: "Monthly (2nd Monday: Aug 10, Sep 14)" }
    ]
  },
  {
    id: "import-sierra-analytical-aliso-viejo-9",
    name: "Sierra Analytical Lab",
    city: "Laguna Hills",
    pricing_model: "per Service",
    cleaner_name: "Luz Uribe",
    hours: 6,
    frequency: "Every 14 days",
    revenue: 533,
    cost: 292.5,
    rate_per_service: 115,
    payment_method: "Check",
    contract_start: "2026-07-09",
    contract_end: null,
    last_contact_date: "2026-02-18",
    last_qcc_date: "2026-04-14",
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "26052 Merit Circle. Cleaning around glass vials on countertops, lobby dusting. Dumpster through back door.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 4, paid_hours: 6, assigned_cleaner_name: "Luz Uribe", frequency_type: "biweekly", anchor_date: "2026-07-09", notes: "Every 14 days (Thursday)" }
    ]
  },
  {
    id: "import-steripax-huntington-beach-36",
    name: "Steripax",
    city: "Huntington Beach",
    pricing_model: "flat rate",
    cleaner_name: "Lucia Portillo",
    hours: 8,
    frequency: "5x per week",
    revenue: 5152.7,
    cost: 3386.06,
    payment_method: "ACH",
    contract_start: "2026-02-23",
    contract_end: "2027-02-23",
    last_contact_date: "2026-02-23",
    last_qcc_date: null,
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "6h on Mon, Tue, Fri; 8h on Wed, Thu (Start: 6:00 AM).",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 1, paid_hours: 6, assigned_cleaner_name: "Lucia Portillo", notes: "Monday 6:00 AM" },
      { day_of_week: 2, paid_hours: 6, assigned_cleaner_name: "Lucia Portillo", notes: "Tuesday 6:00 AM" },
      { day_of_week: 3, paid_hours: 8, assigned_cleaner_name: "Lucia Portillo", notes: "Wednesday 6:00 AM" },
      { day_of_week: 4, paid_hours: 8, assigned_cleaner_name: "Lucia Portillo", notes: "Thursday 6:00 AM" },
      { day_of_week: 5, paid_hours: 6, assigned_cleaner_name: "Lucia Portillo", notes: "Friday 6:00 AM" },
    ]
  },
  {
    id: "import-swing-easy-golf-club-costa-mesa-5",
    name: "Swing Easy Golf Club Costa Mesa",
    city: "Costa Mesa",
    pricing_model: "Flat rate",
    cleaner_name: "Sandra Hernandez",
    hours: 3,
    frequency: "Every week on Wed",
    revenue: 520,
    cost: 299,
    rate_per_service: 69,
    payment_method: "Credit Card",
    contract_start: "2025-12-03",
    contract_end: null,
    last_contact_date: "2026-02-18",
    last_qcc_date: "2026-04-14",
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "2960 Airway Avenue. Key given. Dust monitors & keyboards in hitting bay.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 3, paid_hours: 3, assigned_cleaner_name: "Sandra Hernandez", notes: "Wednesday (Any time)" }
    ]
  },
  {
    id: "import-swing-easy-golf-club-yorba-linda-6",
    name: "Swing Easy Golf Club Yorba Linda",
    city: "Yorba Linda",
    pricing_model: "Flat rate",
    cleaner_name: "Unassigned",
    hours: 3,
    frequency: "Every 14 days",
    revenue: 486,
    cost: 200,
    rate_per_service: 92,
    payment_method: "Credit Card",
    contract_start: "2025-12-04",
    contract_end: null,
    last_contact_date: "2026-02-18",
    last_qcc_date: "2026-04-14",
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "22755 Savi Ranch Parkway. Supplies in bathroom & bar area. Lobby dusting, hitting bay monitors.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 4, paid_hours: 3, assigned_cleaner_name: "Sandra Hernandez", frequency_type: "biweekly", anchor_date: "2025-12-04", notes: "Every 14 days (Thursday)" }
    ]
  },
  {
    id: "import-the-harper-wedding-venue-costa-mesa-33",
    name: "The Harper Wedding Venue",
    city: "Costa Mesa",
    pricing_model: "per Service",
    cleaner_name: "Juan Romero",
    hours: 5,
    frequency: "As needed (Events)",
    revenue: 2990,
    cost: 1170,
    rate_per_service: 92,
    payment_method: "Check",
    contract_start: "2026-02-19",
    contract_end: null,
    last_contact_date: "2026-02-19",
    last_qcc_date: "2026-04-14",
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "$90 payment to Juan Romero per event, $230 charged. Shift: Between 12 AM - 7 AM.",
    source_sheet: "Accounts",
  },
  {
    id: "import-university-park-dental-irvine-10",
    name: "University Park Dental",
    city: "Irvine",
    pricing_model: "per Service",
    cleaner_name: "Unassigned",
    hours: 2.25,
    frequency: "Every 2 weeks",
    revenue: 325,
    cost: 112.13,
    rate_per_service: 51.75,
    payment_method: "Credit Card",
    contract_start: "2025-06-01",
    contract_end: "2027-06-01",
    last_contact_date: null,
    last_qcc_date: "2026-04-13",
    has_supplies: false,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "5321 University Drive Suite A. Meet Tania on Monday mornings 9:30 AM - 11:45 AM. $51.75 labor per service.",
    source_sheet: "Accounts",
    schedule_rules: [
      {
        day_of_week: 1,
        paid_hours: 2.25,
        assigned_cleaner_name: "Unassigned",
        frequency_type: "biweekly",
        anchor_date: "2026-08-31",
        effective_start_date: "2026-08-31",
        notes: "Every 2 weeks (Monday 9:30 AM - 11:45 AM, $51.75 per service)"
      }
    ]
  },
  {
    id: "import-vntr-fitness-rancho-santa-margarita-26",
    name: "VNTR Fitness",
    city: "Rancho Santa Margarita",
    pricing_model: "flat rate",
    cleaner_name: "Ana Morales",
    hours: 2.5,
    frequency: "3x per week",
    revenue: 1258,
    cost: 858,
    rate_per_service: 57.5,
    payment_method: "Credit Card",
    contract_start: "2026-01-06",
    contract_end: null,
    last_contact_date: "2026-02-18",
    last_qcc_date: "2026-04-14",
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "23121 Antonio Parkway. Lockbox code 6077. 8:00 PM - 11:00 PM. Dusting & leaf blower.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 1, paid_hours: 2.5, assigned_cleaner_name: "Ana Morales", notes: "Monday 8:00 PM - 11:00 PM" },
      { day_of_week: 3, paid_hours: 2.5, assigned_cleaner_name: "Ana Morales", notes: "Wednesday 8:00 PM - 11:00 PM" },
      { day_of_week: 5, paid_hours: 2.5, assigned_cleaner_name: "Ana Morales", notes: "Friday 8:00 PM - 11:00 PM" },
    ]
  },
  {
    id: "import-wren-spa-costa-mesa-34",
    name: "Wren Spa",
    city: "Costa Mesa",
    pricing_model: "flat rate",
    cleaner_name: "Luz Uribe",
    hours: 4,
    frequency: "1x per week",
    revenue: 740,
    cost: 399,
    rate_per_service: 92,
    payment_method: "Credit card",
    contract_start: "2026-03-26",
    contract_end: null,
    last_contact_date: null,
    last_qcc_date: null,
    has_supplies: true,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "175 Cabrillo Street. Parking gate: 062789. Alarm: 2789. Back door: 1199. Saunas. Must finish before 8:30 AM.",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 4, paid_hours: 4, assigned_cleaner_name: "Luz Uribe", notes: "Thursday 6:00 AM - 11:30 AM (Finish by 8:30 AM)" }
    ]
  },
  {
    id: "import-lifted-dentistry-irvine",
    name: "Lifted Dentistry",
    city: "Irvine",
    pricing_model: "per service",
    cleaner_name: "Unassigned",
    hours: 3,
    frequency: "Every 14 days",
    revenue: 335,
    cost: 149,
    rate_per_service: 69,
    payment_method: "Zelle",
    contract_start: "2026-08-01",
    contract_end: null,
    last_contact_date: null,
    last_qcc_date: null,
    has_supplies: false,
    has_keys: false,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "Every other week cleaning ($69.00 per service).",
    source_sheet: "Accounts",
    schedule_rules: [
      { day_of_week: 4, paid_hours: 3, assigned_cleaner_name: "Unassigned", frequency_type: "biweekly", frequency_interval: 2, anchor_date: "2026-08-06", notes: "Every 14 days (Thursday)" }
    ]
  },
  {
    id: "import-la-model-unit-cleaning",
    name: "LA Model Unit Cleaning",
    city: "Los Angeles",
    pricing_model: "per Service",
    cleaner_name: "Sandra Hernandez",
    hours: 3.0,
    frequency: "As needed (Events)",
    revenue: 340,
    cost: 170,
    rate_per_service: 170.00,
    payment_method: "Check",
    contract_start: "2026-08-01",
    contract_end: null,
    last_contact_date: null,
    last_qcc_date: null,
    has_supplies: false,
    has_keys: false,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "LA Model Unit Cleaning. $170.00 labor amount per service. Sandra Hernandez.",
    source_sheet: "Accounts",
  },
  {
    id: "import-renewable-farms",
    name: "Renewable Farms",
    city: "Aliso Viejo",
    pricing_model: "per Service",
    cleaner_name: "Ana Morales",
    hours: 3.0,
    frequency: "As needed",
    revenue: 720,
    cost: 324,
    rate_per_service: 69.00,
    payment_method: "Credit Card",
    contract_start: "2025-11-01",
    contract_end: "2026-11-01",
    last_contact_date: "2026-02-18",
    last_qcc_date: null,
    has_supplies: false,
    has_keys: true,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "Aliso Viejo event cleanings. $69.00 labor amount per service (Ana Morales).",
    source_sheet: "Accounts",
  },
  {
    id: "import-revive-real-estate",
    name: "Revive Real Estate",
    city: "Irvine",
    pricing_model: "per Service",
    cleaner_name: "Unassigned",
    hours: 4.0,
    frequency: "As needed",
    revenue: 250,
    cost: 92,
    rate_per_service: 92.00,
    payment_method: "ACH",
    contract_start: "2026-08-01",
    contract_end: null,
    last_contact_date: null,
    last_qcc_date: null,
    has_supplies: false,
    has_keys: false,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "$92.00 labor amount per service (including insurances).",
    source_sheet: "Accounts",
  },
  {
    id: "import-flex-fitness-oc",
    name: "Flex Fitness OC",
    city: "Laguna Hills",
    pricing_model: "per Service",
    cleaner_name: "Unassigned",
    hours: 5.0,
    frequency: "As needed",
    revenue: 300,
    cost: 115,
    rate_per_service: 115.00,
    payment_method: "Credit Card",
    contract_start: "2026-08-01",
    contract_end: null,
    last_contact_date: null,
    last_qcc_date: null,
    has_supplies: false,
    has_keys: false,
    supply_delivery_date: null,
    estimated_fill_date: null,
    supplies_notes: "$115.00 labor amount per service (including insurances).",
    source_sheet: "Accounts",
  },
];

export type ImportedCommercialEventEntry = {
  account_name: string;
  cleaner_name: string;
  work_date: string;
  hours: number;
  notes?: string;
};

export const importedCommercialEventEntries: ImportedCommercialEventEntry[] = [
  // The Harper Wedding Venue August 2026 dates (13 events)
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-08-01", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged)" },
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-08-02", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged)" },
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-08-07", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged)" },
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-08-08", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged)" },
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-08-14", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged)" },
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-08-15", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged - added)" },
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-08-16", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged)" },
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-08-20", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged)" },
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-08-21", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged)" },
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-08-22", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged)" },
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-08-23", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged)" },
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-08-28", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged)" },
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-08-29", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged)" },
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-08-30", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged)" },
  // The Harper Wedding Venue September 2026 dates (7 events)
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-09-05", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged)" },
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-09-06", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged)" },
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-09-11", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged - added)" },
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-09-12", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged)" },
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-09-18", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged)" },
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-09-19", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged)" },
  { account_name: "The Harper Wedding Venue", cleaner_name: "Juan Romero", work_date: "2026-09-26", hours: 5.0, notes: "12 AM - 7 AM ($90 pay | $230 charged)" },
  // Renewable Farms & LA Model
  { account_name: "Renewable Farms", cleaner_name: "Ana Morales", work_date: "2026-08-08", hours: 3.0, notes: "Event clean" },
  { account_name: "Renewable Farms", cleaner_name: "Ana Morales", work_date: "2026-08-22", hours: 3.0, notes: "Event clean" },
  { account_name: "LA Model Unit Cleaning", cleaner_name: "Sandra Hernandez", work_date: "2026-08-11", hours: 3.0, notes: "Event clean" },
];
