export type ImportedCommercialAccount = {
  id: string;
  name: string;
  city: string | null;
  pricing_model: string | null;
  cleaner_name: string | null;
  hours: number | string | null;
  frequency: string | null;
  revenue: number | null;
  cost: number | null;
  payment_method: string | null;
  contract_start: string | null;
  contract_end: string | null;
  last_contact_date: string | null;
  last_qcc_date: string | null;
  has_supplies: boolean;
  has_keys: boolean;
  supply_delivery_date: string | null;
  estimated_fill_date: string | null;
  supplies_notes: string | null;
  source_sheet: string;
};

export const importedCommercialAccounts: ImportedCommercialAccount[] = [
  { id: "import-13demarzo-irvine-31", name: "13demarzo", city: "Irvine", pricing_model: "flat rate", cleaner_name: "Sandra Hernandez", hours: 2, frequency: "5x per week", revenue: 1426, cost: 997, payment_method: "Credit Card", contract_start: "2026-02-08", contract_end: "2027-02-02", last_contact_date: "2026-02-18", last_qcc_date: "2026-04-14", has_supplies: true, has_keys: true, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: null, source_sheet: "Accounts" },
  { id: "import-888-on-main-santa-ana-2", name: "888 On Main", city: "Santa Ana", pricing_model: "Flat rate", cleaner_name: "Ana Morales", hours: 8, frequency: "5x per week", revenue: 4660, cost: 3680, payment_method: "Check", contract_start: "2024-01-02", contract_end: "2026-01-02", last_contact_date: null, last_qcc_date: null, has_supplies: true, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "Imported from hidden Accounts row; Mop, for renewal farms; Account sheet flag: Y", source_sheet: "Accounts hidden row" },
  { id: "import-besst-labs-orange-7", name: "Besst Labs", city: "Orange", pricing_model: "Per Service", cleaner_name: "Sandra Hernandez", hours: 4.5, frequency: "Weekly", revenue: 1095, cost: 439, payment_method: "ACH", contract_start: "2024-03-25", contract_end: "2026-03-25", last_contact_date: "2026-02-18", last_qcc_date: "2026-04-14", has_supplies: true, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "Account sheet flag: N", source_sheet: "Accounts" },
  { id: "import-dr-bagheri-office-irvine-23", name: "Dr. Bagheri Office", city: "Irvine", pricing_model: "per Service", cleaner_name: "Mirna Contreras", hours: 3, frequency: "1x per week", revenue: 563.33, cost: 299.33, payment_method: "Credit Card", contract_start: "2025-11-07", contract_end: "2026-11-01", last_contact_date: null, last_qcc_date: null, has_supplies: false, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "Account sheet flag: Y", source_sheet: "Accounts" },
  { id: "import-elements-dentistry-fountain-valley-17", name: "Elements Dentistry", city: "Fountain Valley", pricing_model: "per Service", cleaner_name: null, hours: 2.5, frequency: "Weekly", revenue: 563, cost: 325, payment_method: null, contract_start: null, contract_end: null, last_contact_date: null, last_qcc_date: null, has_supplies: false, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "Imported from hidden Accounts row", source_sheet: "Accounts hidden row" },
  { id: "import-elevate-aerial-hb-huntington-beach-22", name: "Elevate Aerial HB", city: "Huntington Beach", pricing_model: "Flat rate", cleaner_name: "Luz Uribe", hours: 5, frequency: "1x per week", revenue: 800, cost: 498, payment_method: "Check", contract_start: "2025-12-07", contract_end: "2026-12-01", last_contact_date: "2026-02-18", last_qcc_date: "2026-04-14", has_supplies: true, has_keys: false, supply_delivery_date: "2025-11-17", estimated_fill_date: null, supplies_notes: "Account sheet flag: Y", source_sheet: "Accounts" },
  { id: "import-field-ai-irvine-30", name: "Field AI", city: "Irvine", pricing_model: "flate rate", cleaner_name: "Sandra Hernandez", hours: "2 for trash 6 for full cleaning", frequency: "5x per week", revenue: 2350, cost: 1494, payment_method: "ACH", contract_start: "2026-01-16", contract_end: "2027-01-12", last_contact_date: "2026-02-18", last_qcc_date: "2026-04-14", has_supplies: true, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "Extension cord, for vacuum", source_sheet: "Accounts" },
  { id: "import-flex-fitness-oc-laguna-hills-28", name: "Flex Fitness OC", city: "Laguna Hills", pricing_model: "flat rate", cleaner_name: null, hours: 5, frequency: "3x per week", revenue: 1680, cost: 997, payment_method: null, contract_start: null, contract_end: null, last_contact_date: null, last_qcc_date: null, has_supplies: false, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "Imported from hidden Accounts row", source_sheet: "Accounts hidden row" },
  { id: "import-globar-medspa-costa-mesa-35", name: "GLOBAR Medspa", city: "Costa Mesa", pricing_model: "flat rate", cleaner_name: "Juan Romero", hours: 3, frequency: "2x per week", revenue: 1450, cost: 468, payment_method: "Zelle", contract_start: null, contract_end: null, last_contact_date: null, last_qcc_date: "2026-04-14", has_supplies: false, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "Step ladder, duster extension", source_sheet: "Accounts" },
  { id: "import-green-leaf-botanicals-whittier-8", name: "Green Leaf Botanicals", city: "Whittier", pricing_model: "per Service", cleaner_name: "Lorena Benitez", hours: null, frequency: "Monthly", revenue: 238, cost: 119, payment_method: "Credit Card", contract_start: "2024-06-04", contract_end: "2026-06-04", last_contact_date: "2026-02-18", last_qcc_date: null, has_supplies: false, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "Account sheet flag: N", source_sheet: "Accounts" },
  { id: "import-hurst-siebert-san-clemente-25", name: "Hurst & Siebert", city: "San Clemente", pricing_model: "Flat rate", cleaner_name: null, hours: null, frequency: "1x per week", revenue: 779, cost: 380.64, payment_method: null, contract_start: null, contract_end: null, last_contact_date: null, last_qcc_date: null, has_supplies: false, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "Imported from hidden Accounts row", source_sheet: "Accounts hidden row" },
  { id: "import-ilg-corona-office-corona-19", name: "ILG Corona Office", city: "Corona", pricing_model: "Flat rate", cleaner_name: "Sandra Hernandez", hours: 3, frequency: "3x per week", revenue: 1163, cost: 897, payment_method: "Check", contract_start: "2025-12-01", contract_end: "2026-12-01", last_contact_date: "2026-02-18", last_qcc_date: "2026-03-11", has_supplies: true, has_keys: true, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "Account sheet flag: Y", source_sheet: "Accounts" },
  { id: "import-ilg-irvine-office-irvine-18", name: "ILG Irvine Office", city: "Irvine", pricing_model: "Flat rate", cleaner_name: "Maria Lopez", hours: 4, frequency: "3x per week", revenue: 1800, cost: 1196, payment_method: "Check", contract_start: "2025-12-01", contract_end: "2026-12-01", last_contact_date: "2026-02-18", last_qcc_date: "2026-04-14", has_supplies: true, has_keys: true, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "Account sheet flag: Y", source_sheet: "Accounts" },
  { id: "import-ilg-valencia-office-valencia-21", name: "ILG Valencia Office", city: "Valencia", pricing_model: "Flat rate", cleaner_name: "Emmi Guerra", hours: 4.5, frequency: "3x per week", revenue: 1890, cost: 1345.5, payment_method: "Check", contract_start: "2026-02-02", contract_end: "2027-02-02", last_contact_date: "2026-02-18", last_qcc_date: null, has_supplies: false, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: null, source_sheet: "Accounts" },
  { id: "import-ilg-westlake-westlake-village-20", name: "ILG Westlake", city: "Westlake Village", pricing_model: "Flat rate", cleaner_name: "Emmi Guerra", hours: 2.5, frequency: "3x per week", revenue: 1130, cost: 747.5, payment_method: "Check", contract_start: "2026-02-02", contract_end: "2027-02-02", last_contact_date: "2026-02-18", last_qcc_date: null, has_supplies: false, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: null, source_sheet: "Accounts" },
  { id: "import-kott-koatings-lake-forest-13", name: "Kott Koatings", city: "Lake Forest", pricing_model: "per Service", cleaner_name: "Mirna Contreras", hours: 3, frequency: "Every week", revenue: 606.67, cost: 299, payment_method: "Check", contract_start: "2025-07-28", contract_end: "2026-07-11", last_contact_date: "2026-02-18", last_qcc_date: null, has_supplies: true, has_keys: false, supply_delivery_date: "2026-01-21", estimated_fill_date: null, supplies_notes: "Step Ladder (3 steps) Stainless steel cleaner 1 bottle Extended duster.; 2 vac, 2 buckets. full supplies; Account sheet flag: N", source_sheet: "Accounts" },
  { id: "import-kush-fine-art-laguna-beach-14", name: "Kush Fine Art", city: "Laguna Beach", pricing_model: "per Service", cleaner_name: "Sandra Hernandez", hours: null, frequency: "Every 3 weeks", revenue: 340, cost: 95.31, payment_method: "Credit Card", contract_start: "2025-07-29", contract_end: "2026-07-11", last_contact_date: null, last_qcc_date: null, has_supplies: true, has_keys: false, supply_delivery_date: "2025-08-26", estimated_fill_date: null, supplies_notes: "Account sheet flag: Y", source_sheet: "Accounts" },
  { id: "import-la-model-unit-cleaning-compton-11", name: "LA Model Unit Cleaning", city: "Compton", pricing_model: "per Service", cleaner_name: "Esperanza Youseff", hours: null, frequency: "Weekly", revenue: 1451, cost: 736, payment_method: "Check", contract_start: "2025-07-11", contract_end: "2026-07-11", last_contact_date: "2026-02-18", last_qcc_date: null, has_supplies: false, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "Team supplies sheet cleaner: Esperanza Yoseff; Account sheet flag: Y", source_sheet: "Accounts" },
  { id: "import-macarthur-dental-arts-irvine-37", name: "MacArthur Dental Arts", city: "Irvine", pricing_model: "Flat Rate", cleaner_name: "Kassandra Valentin", hours: 1.5, frequency: "4x per week", revenue: 1060, cost: 746.92, payment_method: "Credit card", contract_start: null, contract_end: null, last_contact_date: null, last_qcc_date: "2026-04-14", has_supplies: true, has_keys: false, supply_delivery_date: "2025-04-12", estimated_fill_date: null, supplies_notes: null, source_sheet: "Accounts" },
  { id: "import-mama-s-restaurant-huntington-beach-3", name: "Mama's Restaurant", city: "Huntington Beach", pricing_model: "Per Service", cleaner_name: "Juan Romero", hours: 11.11, frequency: "Weekly", revenue: 1898, cost: 996, payment_method: "Check", contract_start: "2024-04-01", contract_end: "2026-04-01", last_contact_date: "2026-02-18", last_qcc_date: "2026-04-10", has_supplies: false, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "we provide him with an additional mop bucket.; Account sheet flag: Y", source_sheet: "Accounts" },
  { id: "import-mama-s-restaurant-los-alamitos-4", name: "Mama's Restaurant", city: "Los Alamitos", pricing_model: "Per Service", cleaner_name: "Juan Romero", hours: 11.11, frequency: "Weekly", revenue: 2028, cost: 858, payment_method: "Check", contract_start: "2024-12-01", contract_end: "2025-12-01", last_contact_date: "2026-02-18", last_qcc_date: "2026-04-16", has_supplies: false, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "Account sheet flag: Y", source_sheet: "Accounts" },
  { id: "import-miracle-minds-newport-32", name: "Miracle Minds", city: "Newport", pricing_model: "flate rate", cleaner_name: "Luz Uribe", hours: 3, frequency: "2x per week", revenue: 1250, cost: 597.54, payment_method: "Credit Card", contract_start: "2026-02-10", contract_end: "2027-02-02", last_contact_date: "2026-02-18", last_qcc_date: "2026-03-10", has_supplies: true, has_keys: true, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: null, source_sheet: "Accounts" },
  { id: "import-miwa-office-irvine-27", name: "MIWA Office", city: "Irvine", pricing_model: "per Service", cleaner_name: "Mirna Contreras", hours: 2, frequency: "1x per week", revenue: 480, cost: 239, payment_method: "ACH", contract_start: "2025-12-26", contract_end: "2026-12-01", last_contact_date: null, last_qcc_date: null, has_supplies: true, has_keys: false, supply_delivery_date: "2026-01-21", estimated_fill_date: null, supplies_notes: "Account sheet flag: Y", source_sheet: "Accounts" },
  { id: "import-ocss-office-huntington-beach-29", name: "OCSS Office", city: "Huntington Beach", pricing_model: "flat rate", cleaner_name: "Mirna Contreras", hours: 2.5, frequency: "Twice a month", revenue: 380, cost: 125, payment_method: "Credit Card", contract_start: "2026-01-12", contract_end: "2027-01-12", last_contact_date: null, last_qcc_date: null, has_supplies: true, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: null, source_sheet: "Accounts" },
  { id: "import-orange-county-dermatology-team-supplies-20", name: "Orange County Dermatology", city: null, pricing_model: null, cleaner_name: "Mirna Contreras", hours: null, frequency: null, revenue: null, cost: null, payment_method: null, contract_start: null, contract_end: null, last_contact_date: null, last_qcc_date: null, has_supplies: true, has_keys: false, supply_delivery_date: "2026-01-30", estimated_fill_date: null, supplies_notes: "Full set, plus dry mop and dust extender, and bunch of towels; Flat dust mop, standup vacuum.", source_sheet: "Team supplies" },
  { id: "import-posh-pooch-seal-beach-15", name: "Posh Pooch", city: "Seal Beach", pricing_model: "per Service", cleaner_name: "Luz Uribe", hours: 4, frequency: "Monthly", revenue: 338, cost: 92, payment_method: "Credit Card", contract_start: "2025-08-25", contract_end: "2026-08-25", last_contact_date: "2026-02-18", last_qcc_date: null, has_supplies: true, has_keys: true, supply_delivery_date: "2025-08-26", estimated_fill_date: null, supplies_notes: "Team supplies sheet cleaner: Mirna Contreras; Account sheet flag: N", source_sheet: "Accounts" },
  { id: "import-renewable-farms-aliso-viejo-16", name: "Renewable Farms", city: "Aliso Viejo", pricing_model: "per Service", cleaner_name: "Ana Morales", hours: 3, frequency: "As needed", revenue: 720, cost: 396, payment_method: "Credit Card", contract_start: "2025-11-01", contract_end: "2026-11-01", last_contact_date: "2026-02-18", last_qcc_date: null, has_supplies: true, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "Account sheet flag: Y", source_sheet: "Accounts" },
  { id: "import-revive-real-estate-irvine-24", name: "Revive Real Estate", city: "Irvine", pricing_model: "per Service", cleaner_name: "Sandra Hernandez", hours: 4, frequency: "Every 2 weeks", revenue: 498.33, cost: 199.34, payment_method: "Check", contract_start: "2025-12-01", contract_end: "2026-12-01", last_contact_date: null, last_qcc_date: null, has_supplies: false, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "Imported from hidden Accounts row; Account sheet flag: Y", source_sheet: "Accounts hidden row" },
  { id: "import-sierra-analytical-aliso-viejo-9", name: "Sierra Analytical", city: "Aliso Viejo", pricing_model: "per Service", cleaner_name: "Luz Uribe", hours: 5, frequency: "Every 2 weeks", revenue: 533, cost: 292.5, payment_method: "Check", contract_start: "2025-04-29", contract_end: "2026-04-29", last_contact_date: "2026-02-18", last_qcc_date: null, has_supplies: true, has_keys: false, supply_delivery_date: "2025-07-07", estimated_fill_date: null, supplies_notes: "Account sheet flag: Y", source_sheet: "Accounts" },
  { id: "import-stance-gym-cleaning-san-clemente-12", name: "Stance Gym Cleaning", city: "San Clemente", pricing_model: "per Service", cleaner_name: "Sandra Hernandez", hours: 3, frequency: "3x per week", revenue: 1560, cost: 897, payment_method: "Credit Card", contract_start: "2024-11-12", contract_end: "2026-11-12", last_contact_date: "2026-02-18", last_qcc_date: null, has_supplies: true, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "Imported from hidden Accounts row; Account sheet flag: Y/N Need drew", source_sheet: "Accounts hidden row" },
  { id: "import-steripax-huntington-beach-36", name: "Steripax", city: "Huntington Beach", pricing_model: "flat rate", cleaner_name: "Lucia Portillo", hours: "6 and 8", frequency: "5x per week", revenue: 5152.7, cost: 3386.06, payment_method: "ACH", contract_start: null, contract_end: null, last_contact_date: null, last_qcc_date: "2026-04-13", has_supplies: false, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: null, source_sheet: "Accounts" },
  { id: "import-surf-city-endo-team-supplies-14", name: "Surf City Endo", city: null, pricing_model: null, cleaner_name: "Mirna Contreras", hours: null, frequency: null, revenue: null, cost: null, payment_method: null, contract_start: null, contract_end: null, last_contact_date: null, last_qcc_date: null, has_supplies: true, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "Imported from Team supplies sheet only", source_sheet: "Team supplies" },
  { id: "import-swing-easy-golf-club-costa-mesa-5", name: "Swing Easy Golf Club", city: "Costa Mesa", pricing_model: "Flat rate", cleaner_name: "Sandra Hernandez", hours: 3, frequency: "Weekly", revenue: 520, cost: 299, payment_method: "Credit Card", contract_start: "2025-05-01", contract_end: "2026-05-01", last_contact_date: "2026-04-15", last_qcc_date: "2026-03-12", has_supplies: true, has_keys: true, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "Account sheet flag: Y", source_sheet: "Accounts" },
  { id: "import-swing-easy-golf-club-yorba-linda-6", name: "Swing Easy Golf Club", city: "Yorba Linda", pricing_model: "Flat rate", cleaner_name: "Sandra Hernandez", hours: 4, frequency: "Every 2 weeks", revenue: 486, cost: 200, payment_method: "Credit Card", contract_start: "2025-04-11", contract_end: "2026-04-11", last_contact_date: "2026-04-15", last_qcc_date: "2026-03-12", has_supplies: true, has_keys: true, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "Account sheet flag: Y", source_sheet: "Accounts" },
  { id: "import-the-harper-wedding-venue-costa-mesa-33", name: "The Harper Wedding Venue", city: "Costa Mesa", pricing_model: "per Service", cleaner_name: "Juan Romero", hours: 4, frequency: "As needed", revenue: 2300, cost: 920, payment_method: "Check", contract_start: null, contract_end: null, last_contact_date: null, last_qcc_date: "2026-04-18", has_supplies: false, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: "mop bucket", source_sheet: "Accounts" },
  { id: "import-university-park-dental-irvine-10", name: "University Park Dental", city: "Irvine", pricing_model: "per Service", cleaner_name: "Mirna Contreras", hours: 2.25, frequency: "Every 2 weeks", revenue: 325, cost: 112.13, payment_method: "Credit Card", contract_start: "2025-06-07", contract_end: "2026-06-07", last_contact_date: null, last_qcc_date: "2026-04-13", has_supplies: true, has_keys: false, supply_delivery_date: "2025-07-07", estimated_fill_date: null, supplies_notes: "Account sheet flag: Y", source_sheet: "Accounts" },
  { id: "import-vntr-fitness-rancho-santa-margarita-26", name: "VNTR Fitness", city: "Rancho Santa Margarita", pricing_model: "flat rate", cleaner_name: "Luz Uribe", hours: 2.5, frequency: "3x per week", revenue: 1258, cost: 858, payment_method: "Credit Card", contract_start: "2026-01-12", contract_end: "2027-01-12", last_contact_date: null, last_qcc_date: "2026-04-20", has_supplies: true, has_keys: true, supply_delivery_date: "2025-01-10", estimated_fill_date: "Only vacuum", supplies_notes: "Team supplies sheet cleaner: Ana Morales", source_sheet: "Accounts" },
  { id: "import-wren-spa-costa-mesa-34", name: "Wren Spa", city: "Costa Mesa", pricing_model: "flat rate", cleaner_name: "Luz Uribe", hours: 3, frequency: "1x per week", revenue: 740, cost: 399, payment_method: "Credit card", contract_start: null, contract_end: null, last_contact_date: null, last_qcc_date: "2026-04-09", has_supplies: true, has_keys: false, supply_delivery_date: null, estimated_fill_date: null, supplies_notes: null, source_sheet: "Accounts" },
];
