import { computeBookingFormulas } from "./calculator";
import type { ServiceBookingRow, ServiceCategory } from "./types";

// Helper: parse "H:MM" duration string to decimal hours
function parseDuration(s: string): number {
  if (!s || s === "0:00") return 0;
  const [h, m] = s.split(":").map(Number);
  return (h || 0) + (m || 0) / 60;
}

// Helper: map CSV Frequency to ServiceCategory
function mapCategory(service: string, freq: string): ServiceCategory {
  if (service === "Commercial Cleaning") return "Commercial Cleaning";
  if (service === "Move In/Out Clean") return "Move In/Out Clean";
  if (service === "Deep Clean") return "Deep Clean";
  // Express Clean / Standard Clean → categorize by frequency
  if (freq === "Weekly") return "Weekly";
  if (freq === "Every Other Week") return "Biweekly";
  if (freq === "Every 3 Weeks") return "Triweekly";
  if (freq === "Monthly") return "Monthly";
  return "Standard Clean";
}

// Helper: map CSV Frequency to tracker frequency label
function mapFrequency(freq: string): string {
  const map: Record<string, string> = {
    "One-Time": "One Time",
    "Weekly": "Weekly",
    "Every Other Week": "Every Other Week",
    "Every 3 Weeks": "Every 3 Weeks",
    "Monthly": "Monthly",
  };
  return map[freq] ?? freq;
}

// Helper: strip leading provider ID "268: Maria Lopez" → "Maria Lopez"
function cleanerName(raw: string): string {
  if (!raw || raw === "Unassigned") return "Unassigned";
  return raw.replace(/^\d+:\s*/, "").trim();
}

export const augustResidentialBookings: ServiceBookingRow[] = [
  // 08/01 — Brian Metcalf — Move In/Out
  computeBookingFormulas({
    id: "aug-11475",
    date: "2026-08-01",
    clientName: "Brian Metcalf",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Newport Beach",
    cleanerTeam: "Maria Lopez",
    subTotal: 590,
    salesTax: 0,
    processingFee: 17.7,
    tip: 0,
    teamEarningsWithoutTips: 350,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("3:30"),
    actualHours: parseDuration("3:30"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/01 — Sonia Kim — Move In/Out
  computeBookingFormulas({
    id: "aug-11479",
    date: "2026-08-01",
    clientName: "Sonia Kim",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Fullerton",
    cleanerTeam: "Miriam Lopez",
    subTotal: 469,
    salesTax: 0,
    processingFee: 14.07,
    tip: 0,
    teamEarningsWithoutTips: 185,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("3:00"),
    actualHours: parseDuration("3:00"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/04 — Suneil Agrawal — Weekly Express
  computeBookingFormulas({
    id: "aug-10650",
    date: "2026-08-04",
    clientName: "Suneil Agrawal",
    service: "Express Clean",
    serviceCategory: "Weekly",
    frequency: "Weekly",
    city: "Yorba Linda",
    cleanerTeam: "Rosa Calderon",
    subTotal: 224,
    salesTax: 6.72,
    processingFee: 6.72,
    tip: 0,
    teamEarningsWithoutTips: 120,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:15"),
    actualHours: parseDuration("2:15"),
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/05 — Miki Stokes — Weekly Express
  computeBookingFormulas({
    id: "aug-11134",
    date: "2026-08-05",
    clientName: "Miki Stokes",
    service: "Express Clean",
    serviceCategory: "Weekly",
    frequency: "Weekly",
    city: "Ladera Ranch",
    cleanerTeam: "Juan Romero",
    subTotal: 680,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 310,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("5:30"),
    actualHours: parseDuration("5:30"),
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/05 — Takeo Fujimoto — Biweekly Express
  computeBookingFormulas({
    id: "aug-10117",
    date: "2026-08-05",
    clientName: "Takeo Fujimoto",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Irvine",
    cleanerTeam: "Lorena Benitez",
    subTotal: 156,
    salesTax: 4.68,
    processingFee: 4.68,
    tip: 0,
    teamEarningsWithoutTips: 78,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:00"),
    actualHours: parseDuration("2:00"),
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/05 — Rob Catena — Deep Clean One-Time
  computeBookingFormulas({
    id: "aug-11465",
    date: "2026-08-05",
    clientName: "Rob Catena",
    service: "Deep Clean",
    serviceCategory: "Deep Clean",
    frequency: "One Time",
    city: "Coto de Caza",
    cleanerTeam: "Miriam Lopez",
    subTotal: 655,
    salesTax: 0,
    processingFee: 19.65,
    tip: 0,
    teamEarningsWithoutTips: 260,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("4:00"),
    actualHours: parseDuration("4:00"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/05 — Linda Matias — One-Time Express
  computeBookingFormulas({
    id: "aug-11087",
    date: "2026-08-05",
    clientName: "Linda Matias",
    service: "Express Clean",
    serviceCategory: "Standard Clean",
    frequency: "One Time",
    city: "Laguna Beach",
    cleanerTeam: "Gabriel Cardenas",
    subTotal: 135,
    salesTax: 4.05,
    processingFee: 4.05,
    tip: 0,
    teamEarningsWithoutTips: 85,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:15"),
    actualHours: parseDuration("2:15"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/06 — Britt Cottrill — One-Time Express (unpaid)
  computeBookingFormulas({
    id: "aug-11612",
    date: "2026-08-06",
    clientName: "Britt Cottrill",
    service: "Express Clean",
    serviceCategory: "Standard Clean",
    frequency: "One Time",
    city: "Newport Beach",
    cleanerTeam: "Juan Romero",
    subTotal: 560,
    salesTax: 0,
    processingFee: 17.25,
    tip: 0,
    teamEarningsWithoutTips: 300,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("6:00"),
    actualHours: parseDuration("6:00"),
    bookedBy: "Online Booking",
    status: "scheduled",
  }),
  // 08/06 — Kyle Digiantonio — Move In/Out
  computeBookingFormulas({
    id: "aug-11497",
    date: "2026-08-06",
    clientName: "Kyle Digiantonio",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Costa Mesa",
    cleanerTeam: "Dovissy Calderon",
    subTotal: 973.58,
    salesTax: 0,
    processingFee: 29.21,
    tip: 0,
    teamEarningsWithoutTips: 500,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("3:30"),
    actualHours: parseDuration("3:30"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/06 — Sierra Analytical Lab — Commercial
  computeBookingFormulas({
    id: "aug-11271",
    date: "2026-08-06",
    clientName: "Sierra Analytical Lab",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "Every Other Week",
    city: "Laguna Hills",
    cleanerTeam: "Unassigned",
    subTotal: 246,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("1:30"),
    actualHours: parseDuration("1:30"),
    bookedBy: "Commercial Contract",
    status: "scheduled",
  }),
  // 08/07 — Larry Silfen — Biweekly Express
  computeBookingFormulas({
    id: "aug-11507",
    date: "2026-08-07",
    clientName: "Larry Silfen",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Ladera Ranch",
    cleanerTeam: "Blanca Garcia",
    subTotal: 240,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 200,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("4:30"),
    actualHours: parseDuration("4:30"),
    bookedBy: "Subscription",
    status: "scheduled",
  }),
  // 08/07 — James Bae — Biweekly Express (unassigned)
  computeBookingFormulas({
    id: "aug-10542",
    date: "2026-08-07",
    clientName: "James Bae",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Costa Mesa",
    cleanerTeam: "Unassigned",
    subTotal: 140,
    salesTax: 4.2,
    processingFee: 4.2,
    tip: 0,
    teamEarningsWithoutTips: 0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 0,
    actualHours: 0,
    bookedBy: "Subscription",
    status: "scheduled",
  }),
  // 08/07 — Lindsay Mullen — Every 3 Weeks Express
  computeBookingFormulas({
    id: "aug-10571",
    date: "2026-08-07",
    clientName: "Lindsay Mullen",
    service: "Express Clean",
    serviceCategory: "Triweekly",
    frequency: "Every 3 Weeks",
    city: "Long Beach",
    cleanerTeam: "Gabriel Cardenas",
    subTotal: 225,
    salesTax: 6.75,
    processingFee: 6.75,
    tip: 0,
    teamEarningsWithoutTips: 120,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:15"),
    actualHours: parseDuration("2:15"),
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/07 — Shaila Emani — Move In/Out
  computeBookingFormulas({
    id: "aug-11484",
    date: "2026-08-07",
    clientName: "Shaila Emani",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Irvine",
    cleanerTeam: "Miriam Lopez",
    subTotal: 349,
    salesTax: 0,
    processingFee: 10.47,
    tip: 0,
    teamEarningsWithoutTips: 140,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:30"),
    actualHours: parseDuration("2:30"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/07 — Zach Renderos — Biweekly Express
  computeBookingFormulas({
    id: "aug-11037",
    date: "2026-08-07",
    clientName: "Zach Renderos",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Santa Ana",
    cleanerTeam: "Lorena Benitez",
    subTotal: 220,
    salesTax: 6.6,
    processingFee: 6.6,
    tip: 0,
    teamEarningsWithoutTips: 100,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:15"),
    actualHours: parseDuration("2:15"),
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/09 — Renewable Farms — Commercial
  computeBookingFormulas({
    id: "aug-11376",
    date: "2026-08-09",
    clientName: "Renewable Farms",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "One Time",
    city: "Aliso Viejo",
    cleanerTeam: "Ana Morales",
    subTotal: 120,
    salesTax: 3.6,
    processingFee: 3.6,
    tip: 0,
    teamEarningsWithoutTips: 0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("0:45"),
    actualHours: parseDuration("0:45"),
    bookedBy: "Commercial Contract",
    status: "completed",
  }),
  // 08/09 — Tongsu Hong — Move In/Out
  computeBookingFormulas({
    id: "aug-11492",
    date: "2026-08-09",
    clientName: "Tongsu Hong",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Irvine",
    cleanerTeam: "Miriam Lopez",
    subTotal: 319,
    salesTax: 0,
    processingFee: 9.57,
    tip: 0,
    teamEarningsWithoutTips: 125,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:30"),
    actualHours: parseDuration("2:30"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/10 — Suneil Agrawal — Weekly Express
  computeBookingFormulas({
    id: "aug-10651",
    date: "2026-08-10",
    clientName: "Suneil Agrawal",
    service: "Express Clean",
    serviceCategory: "Weekly",
    frequency: "Weekly",
    city: "Yorba Linda",
    cleanerTeam: "Rosa Calderon",
    subTotal: 224,
    salesTax: 6.72,
    processingFee: 6.72,
    tip: 0,
    teamEarningsWithoutTips: 120,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:15"),
    actualHours: parseDuration("2:15"),
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/12 — Britt Cottrill — One-Time Express
  computeBookingFormulas({
    id: "aug-11438",
    date: "2026-08-12",
    clientName: "Britt Cottrill",
    service: "Express Clean",
    serviceCategory: "Standard Clean",
    frequency: "One Time",
    city: "Newport Beach",
    cleanerTeam: "Jasmine Cardenas",
    subTotal: 560,
    salesTax: 0,
    processingFee: 17.25,
    tip: 0,
    teamEarningsWithoutTips: 300,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("6:00"),
    actualHours: parseDuration("6:00"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/13 — Grace Lawler — Biweekly Express
  computeBookingFormulas({
    id: "aug-10143",
    date: "2026-08-13",
    clientName: "Grace Lawler",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Irvine",
    cleanerTeam: "Juan Romero",
    subTotal: 250,
    salesTax: 7.5,
    processingFee: 7.5,
    tip: 0,
    teamEarningsWithoutTips: 130,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:45"),
    actualHours: parseDuration("2:45"),
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/14 — Kari Kangas — Biweekly Express
  computeBookingFormulas({
    id: "aug-10165",
    date: "2026-08-14",
    clientName: "Kari Kangas",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Laguna Niguel",
    cleanerTeam: "Juan Romero",
    subTotal: 285,
    salesTax: 8.55,
    processingFee: 8.55,
    tip: 0,
    teamEarningsWithoutTips: 140,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("4:00"),
    actualHours: parseDuration("4:00"),
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/14 — Sonya Park — Deep Clean
  computeBookingFormulas({
    id: "aug-11532",
    date: "2026-08-14",
    clientName: "Sonya Park",
    service: "Deep Clean",
    serviceCategory: "Deep Clean",
    frequency: "One Time",
    city: "Irvine",
    cleanerTeam: "Miriam Lopez",
    subTotal: 300,
    salesTax: 9,
    processingFee: 9,
    tip: 0,
    teamEarningsWithoutTips: 120,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:00"),
    actualHours: parseDuration("2:00"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/14 — Rachel Akiyama — Biweekly Express (unassigned)
  computeBookingFormulas({
    id: "aug-10690",
    date: "2026-08-14",
    clientName: "Rachel Akiyama",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Mission Viejo",
    cleanerTeam: "Unassigned",
    subTotal: 408,
    salesTax: 12.24,
    processingFee: 12.24,
    tip: 0,
    teamEarningsWithoutTips: 0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:45"),
    actualHours: parseDuration("2:45"),
    bookedBy: "Subscription",
    status: "scheduled",
  }),
  // 08/14 — Katarzyna Mcnaughton — Biweekly Express
  computeBookingFormulas({
    id: "aug-10227",
    date: "2026-08-14",
    clientName: "Katarzyna Mcnaughton",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Irvine",
    cleanerTeam: "Lorena Benitez",
    subTotal: 308,
    salesTax: 9.24,
    processingFee: 9.24,
    tip: 0,
    teamEarningsWithoutTips: 154,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("4:00"),
    actualHours: parseDuration("4:00"),
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/15 — Renewable Farms — Commercial
  computeBookingFormulas({
    id: "aug-11380",
    date: "2026-08-15",
    clientName: "Renewable Farms",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "One Time",
    city: "Aliso Viejo",
    cleanerTeam: "Ana Morales",
    subTotal: 120,
    salesTax: 3.6,
    processingFee: 3.6,
    tip: 0,
    teamEarningsWithoutTips: 0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("0:45"),
    actualHours: parseDuration("0:45"),
    bookedBy: "Commercial Contract",
    status: "completed",
  }),
  // 08/16 — Chris Chambers — Move In/Out
  computeBookingFormulas({
    id: "aug-11539",
    date: "2026-08-16",
    clientName: "Chris Chambers",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Fullerton",
    cleanerTeam: "Jasmine Cardenas",
    subTotal: 509,
    salesTax: 0,
    processingFee: 15.27,
    tip: 0,
    teamEarningsWithoutTips: 220,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("3:00"),
    actualHours: parseDuration("3:00"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/17 — Linda Matias — One-Time Express
  computeBookingFormulas({
    id: "aug-11397",
    date: "2026-08-17",
    clientName: "Linda Matias",
    service: "Express Clean",
    serviceCategory: "Standard Clean",
    frequency: "One Time",
    city: "Laguna Beach",
    cleanerTeam: "Blanca Garcia",
    subTotal: 230,
    salesTax: 6.9,
    processingFee: 6.9,
    tip: 0,
    teamEarningsWithoutTips: 180,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:15"),
    actualHours: parseDuration("2:15"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/18 — Stephanie Deluna — Move In/Out
  computeBookingFormulas({
    id: "aug-11541",
    date: "2026-08-18",
    clientName: "Stephanie Deluna",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Whittier",
    cleanerTeam: "Juan Romero",
    subTotal: 395,
    salesTax: 0,
    processingFee: 11.85,
    tip: 0,
    teamEarningsWithoutTips: 197.5,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:45"),
    actualHours: parseDuration("2:45"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/18 — Suneil Agrawal — Weekly Express
  computeBookingFormulas({
    id: "aug-10721",
    date: "2026-08-18",
    clientName: "Suneil Agrawal",
    service: "Express Clean",
    serviceCategory: "Weekly",
    frequency: "Weekly",
    city: "Yorba Linda",
    cleanerTeam: "Rosa Calderon",
    subTotal: 224,
    salesTax: 6.72,
    processingFee: 6.72,
    tip: 0,
    teamEarningsWithoutTips: 120,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:15"),
    actualHours: parseDuration("2:15"),
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/20 — Britt Cottrill — One-Time Express
  computeBookingFormulas({
    id: "aug-11540",
    date: "2026-08-20",
    clientName: "Britt Cottrill",
    service: "Express Clean",
    serviceCategory: "Standard Clean",
    frequency: "One Time",
    city: "Newport Beach",
    cleanerTeam: "Juan Romero",
    subTotal: 560,
    salesTax: 0,
    processingFee: 17.25,
    tip: 0,
    teamEarningsWithoutTips: 300,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("6:00"),
    actualHours: parseDuration("6:00"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/20 — Sierra Analytical Lab — Commercial
  computeBookingFormulas({
    id: "aug-11272",
    date: "2026-08-20",
    clientName: "Sierra Analytical Lab",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "Every Other Week",
    city: "Laguna Hills",
    cleanerTeam: "Unassigned",
    subTotal: 246,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("1:30"),
    actualHours: parseDuration("1:30"),
    bookedBy: "Commercial Contract",
    status: "scheduled",
  }),
  // 08/20 — Emily Flowers — Move In/Out
  computeBookingFormulas({
    id: "aug-11551",
    date: "2026-08-20",
    clientName: "Emily Flowers",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Irvine",
    cleanerTeam: "Blanca Garcia",
    subTotal: 374,
    salesTax: 0,
    processingFee: 12.72,
    tip: 0,
    teamEarningsWithoutTips: 170,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:45"),
    actualHours: parseDuration("2:45"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/21 — Julianna Sockol — Move In/Out
  computeBookingFormulas({
    id: "aug-11542",
    date: "2026-08-21",
    clientName: "Julianna Sockol",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Orange",
    cleanerTeam: "Lorena Benitez",
    subTotal: 479,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 175,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("3:00"),
    actualHours: parseDuration("3:00"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/21 — Zach Renderos — Biweekly Express
  computeBookingFormulas({
    id: "aug-11038",
    date: "2026-08-21",
    clientName: "Zach Renderos",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Santa Ana",
    cleanerTeam: "Lorena Benitez",
    subTotal: 220,
    salesTax: 6.6,
    processingFee: 6.6,
    tip: 0,
    teamEarningsWithoutTips: 100,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:15"),
    actualHours: parseDuration("2:15"),
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/21 — Britt Cottrill — One-Time Express
  computeBookingFormulas({
    id: "aug-11564",
    date: "2026-08-21",
    clientName: "Britt Cottrill",
    service: "Express Clean",
    serviceCategory: "Standard Clean",
    frequency: "One Time",
    city: "Newport Beach",
    cleanerTeam: "Juan Romero",
    subTotal: 560,
    salesTax: 0,
    processingFee: 18.75,
    tip: 0,
    teamEarningsWithoutTips: 300,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("6:00"),
    actualHours: parseDuration("6:00"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/21 — Jeremy Wayland — Move In/Out (unpaid)
  computeBookingFormulas({
    id: "aug-11550",
    date: "2026-08-21",
    clientName: "Jeremy Wayland",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Orange",
    cleanerTeam: "Jasmine Cardenas",
    subTotal: 415,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 200,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:45"),
    actualHours: parseDuration("2:45"),
    bookedBy: "Online Booking",
    status: "scheduled",
  }),
  // 08/22 — Renewable Farms — Commercial
  computeBookingFormulas({
    id: "aug-11384",
    date: "2026-08-22",
    clientName: "Renewable Farms",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "One Time",
    city: "Aliso Viejo",
    cleanerTeam: "Ana Morales",
    subTotal: 120,
    salesTax: 3.6,
    processingFee: 3.6,
    tip: 0,
    teamEarningsWithoutTips: 0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:00"),
    actualHours: parseDuration("2:00"),
    bookedBy: "Commercial Contract",
    status: "completed",
  }),
  // 08/22 — Levi Archuleta — Move In/Out (unpaid)
  computeBookingFormulas({
    id: "aug-11543",
    date: "2026-08-22",
    clientName: "Levi Archuleta",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "San Clemente",
    cleanerTeam: "Unassigned",
    subTotal: 1317,
    salesTax: 0,
    processingFee: 39.51,
    tip: 0,
    teamEarningsWithoutTips: 0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("4:00"),
    actualHours: parseDuration("4:00"),
    bookedBy: "Online Booking",
    status: "scheduled",
  }),
  // 08/23 — Linda Matias — One-Time Express
  computeBookingFormulas({
    id: "aug-11502",
    date: "2026-08-23",
    clientName: "Linda Matias",
    service: "Express Clean",
    serviceCategory: "Standard Clean",
    frequency: "One Time",
    city: "Laguna Beach",
    cleanerTeam: "Blanca Garcia",
    subTotal: 135,
    salesTax: 4.05,
    processingFee: 4.05,
    tip: 0,
    teamEarningsWithoutTips: 130,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:15"),
    actualHours: parseDuration("2:15"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/24 — Gavriella Youngs — Biweekly Express (unassigned)
  computeBookingFormulas({
    id: "aug-10228",
    date: "2026-08-24",
    clientName: "Gavriella Youngs",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Rancho Santa Margarita",
    cleanerTeam: "Unassigned",
    subTotal: 220,
    salesTax: 6.6,
    processingFee: 6.6,
    tip: 0,
    teamEarningsWithoutTips: 0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:45"),
    actualHours: parseDuration("2:45"),
    bookedBy: "Subscription",
    status: "scheduled",
  }),
  // 08/24 — Britt Cottrill — One-Time Express (unassigned unpaid)
  computeBookingFormulas({
    id: "aug-11576",
    date: "2026-08-24",
    clientName: "Britt Cottrill",
    service: "Express Clean",
    serviceCategory: "Standard Clean",
    frequency: "One Time",
    city: "Newport Beach",
    cleanerTeam: "Blanca Garcia",
    subTotal: 560,
    salesTax: 0,
    processingFee: 17.25,
    tip: 0,
    teamEarningsWithoutTips: 300,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("6:00"),
    actualHours: parseDuration("6:00"),
    bookedBy: "Online Booking",
    status: "scheduled",
  }),
  // 08/25 — Suneil Agrawal — Weekly Express
  computeBookingFormulas({
    id: "aug-10760",
    date: "2026-08-25",
    clientName: "Suneil Agrawal",
    service: "Express Clean",
    serviceCategory: "Weekly",
    frequency: "Weekly",
    city: "Yorba Linda",
    cleanerTeam: "Rosa Calderon",
    subTotal: 224,
    salesTax: 6.72,
    processingFee: 6.72,
    tip: 0,
    teamEarningsWithoutTips: 120,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:15"),
    actualHours: parseDuration("2:15"),
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/25 — Teresa West — Move In/Out
  computeBookingFormulas({
    id: "aug-11536",
    date: "2026-08-25",
    clientName: "Teresa West",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Orange",
    cleanerTeam: "Lorena Benitez",
    subTotal: 289,
    salesTax: 0,
    processingFee: 8.67,
    tip: 0,
    teamEarningsWithoutTips: 115,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:30"),
    actualHours: parseDuration("2:30"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/25 — Chiaka Ogbogu — Move In/Out
  computeBookingFormulas({
    id: "aug-11579",
    date: "2026-08-25",
    clientName: "Chiaka Ogbogu",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Irvine",
    cleanerTeam: "Miriam Lopez",
    subTotal: 345,
    salesTax: 0,
    processingFee: 10.35,
    tip: 0,
    teamEarningsWithoutTips: 130,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:45"),
    actualHours: parseDuration("2:45"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/25 — Britt Cottrill — One-Time Express (unpaid)
  computeBookingFormulas({
    id: "aug-11575",
    date: "2026-08-25",
    clientName: "Britt Cottrill",
    service: "Express Clean",
    serviceCategory: "Standard Clean",
    frequency: "One Time",
    city: "Newport Beach",
    cleanerTeam: "Juan Romero",
    subTotal: 560,
    salesTax: 0,
    processingFee: 17.25,
    tip: 0,
    teamEarningsWithoutTips: 300,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("6:00"),
    actualHours: parseDuration("6:00"),
    bookedBy: "Online Booking",
    status: "scheduled",
  }),
  // 08/25 — Catherine Maller — Monthly Commercial
  computeBookingFormulas({
    id: "aug-10112",
    date: "2026-08-25",
    clientName: "Catherine Maller",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "Monthly",
    city: "Whittier",
    cleanerTeam: "Lorena Benitez",
    subTotal: 238,
    salesTax: 0,
    processingFee: 7.14,
    tip: 0,
    teamEarningsWithoutTips: 119,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("3:00"),
    actualHours: parseDuration("3:00"),
    bookedBy: "Commercial Contract",
    status: "completed",
  }),
  // 08/26 — Miki Stokes — Weekly Express
  computeBookingFormulas({
    id: "aug-11247",
    date: "2026-08-26",
    clientName: "Miki Stokes",
    service: "Express Clean",
    serviceCategory: "Weekly",
    frequency: "Weekly",
    city: "Ladera Ranch",
    cleanerTeam: "Juan Romero",
    subTotal: 680,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 310,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("5:30"),
    actualHours: parseDuration("5:30"),
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/26 — Takeo Fujimoto — Biweekly Express
  computeBookingFormulas({
    id: "aug-10195",
    date: "2026-08-26",
    clientName: "Takeo Fujimoto",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Irvine",
    cleanerTeam: "Lorena Benitez",
    subTotal: 156,
    salesTax: 4.68,
    processingFee: 4.68,
    tip: 0,
    teamEarningsWithoutTips: 78,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:00"),
    actualHours: parseDuration("2:00"),
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/27 — Allison Korkmaz — Move In/Out (unpaid)
  computeBookingFormulas({
    id: "aug-11578",
    date: "2026-08-27",
    clientName: "Allison Korkmaz",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "San Clemente",
    cleanerTeam: "Blanca Garcia",
    subTotal: 380,
    salesTax: 0,
    processingFee: 11.4,
    tip: 0,
    teamEarningsWithoutTips: 200,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:30"),
    actualHours: parseDuration("2:30"),
    bookedBy: "Online Booking",
    status: "scheduled",
  }),
  // 08/27 — Grace Lawler — Biweekly Express
  computeBookingFormulas({
    id: "aug-10222",
    date: "2026-08-27",
    clientName: "Grace Lawler",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Irvine",
    cleanerTeam: "Juan Romero",
    subTotal: 250,
    salesTax: 7.5,
    processingFee: 7.5,
    tip: 0,
    teamEarningsWithoutTips: 130,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:45"),
    actualHours: parseDuration("2:45"),
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/28 — Kari Kangas — Biweekly Express
  computeBookingFormulas({
    id: "aug-10266",
    date: "2026-08-28",
    clientName: "Kari Kangas",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Laguna Niguel",
    cleanerTeam: "Juan Romero",
    subTotal: 285,
    salesTax: 8.55,
    processingFee: 8.55,
    tip: 0,
    teamEarningsWithoutTips: 140,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("4:00"),
    actualHours: parseDuration("4:00"),
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/28 — Rachel Akiyama — Biweekly Express (unassigned, unpaid)
  computeBookingFormulas({
    id: "aug-10691",
    date: "2026-08-28",
    clientName: "Rachel Akiyama",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Mission Viejo",
    cleanerTeam: "Unassigned",
    subTotal: 408,
    salesTax: 12.24,
    processingFee: 12.24,
    tip: 0,
    teamEarningsWithoutTips: 0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:45"),
    actualHours: parseDuration("2:45"),
    bookedBy: "Subscription",
    status: "scheduled",
  }),
  // 08/28 — Katarzyna Mcnaughton — Biweekly Express (unpaid)
  computeBookingFormulas({
    id: "aug-10323",
    date: "2026-08-28",
    clientName: "Katarzyna Mcnaughton",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Irvine",
    cleanerTeam: "Lorena Benitez",
    subTotal: 308,
    salesTax: 9.24,
    processingFee: 9.24,
    tip: 0,
    teamEarningsWithoutTips: 154,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("4:00"),
    actualHours: parseDuration("4:00"),
    bookedBy: "Subscription",
    status: "scheduled",
  }),
  // 08/28 — Lindsay Mullen — Every 3 Weeks Express
  computeBookingFormulas({
    id: "aug-10572",
    date: "2026-08-28",
    clientName: "Lindsay Mullen",
    service: "Express Clean",
    serviceCategory: "Triweekly",
    frequency: "Every 3 Weeks",
    city: "Long Beach",
    cleanerTeam: "Gabriel Cardenas",
    subTotal: 225,
    salesTax: 6.75,
    processingFee: 6.75,
    tip: 0,
    teamEarningsWithoutTips: 120,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:15"),
    actualHours: parseDuration("2:15"),
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/28 — Linda Matias — One-Time Express
  computeBookingFormulas({
    id: "aug-11405",
    date: "2026-08-28",
    clientName: "Linda Matias",
    service: "Express Clean",
    serviceCategory: "Standard Clean",
    frequency: "One Time",
    city: "Laguna Beach",
    cleanerTeam: "Blanca Garcia",
    subTotal: 135,
    salesTax: 4.05,
    processingFee: 4.05,
    tip: 0,
    teamEarningsWithoutTips: 120,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:15"),
    actualHours: parseDuration("2:15"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/29 — Keith Delossantos — Monthly Deep Clean
  computeBookingFormulas({
    id: "aug-11567",
    date: "2026-08-29",
    clientName: "Keith Delossantos",
    service: "Deep Clean",
    serviceCategory: "Deep Clean",
    frequency: "Monthly",
    city: "Irvine",
    cleanerTeam: "Miriam Lopez",
    subTotal: 230,
    salesTax: 0,
    processingFee: 6.9,
    tip: 0,
    teamEarningsWithoutTips: 90,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:00"),
    actualHours: parseDuration("2:00"),
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/29 — Ava Phillips — One-Time Deep Clean
  computeBookingFormulas({
    id: "aug-11604",
    date: "2026-08-29",
    clientName: "Ava Phillips",
    service: "Deep Clean",
    serviceCategory: "Deep Clean",
    frequency: "One Time",
    city: "Irvine",
    cleanerTeam: "Miriam Lopez",
    subTotal: 260,
    salesTax: 0,
    processingFee: 7.8,
    tip: 0,
    teamEarningsWithoutTips: 105,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:00"),
    actualHours: parseDuration("2:00"),
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/30 — Renewable Farms — Commercial
  computeBookingFormulas({
    id: "aug-11388",
    date: "2026-08-30",
    clientName: "Renewable Farms",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "One Time",
    city: "Aliso Viejo",
    cleanerTeam: "Ana Morales",
    subTotal: 120,
    salesTax: 3.6,
    processingFee: 3.6,
    tip: 0,
    teamEarningsWithoutTips: 0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("0:45"),
    actualHours: parseDuration("0:45"),
    bookedBy: "Commercial Contract",
    status: "completed",
  }),
  // 08/30 — Bill Krause — One-Time Deep Clean (unpaid)
  computeBookingFormulas({
    id: "aug-11611",
    date: "2026-08-30",
    clientName: "Bill Krause",
    service: "Deep Clean",
    serviceCategory: "Deep Clean",
    frequency: "One Time",
    city: "Laguna Niguel",
    cleanerTeam: "Unassigned",
    subTotal: 555,
    salesTax: 0,
    processingFee: 16.65,
    tip: 0,
    teamEarningsWithoutTips: 0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("3:30"),
    actualHours: parseDuration("3:30"),
    bookedBy: "Online Booking",
    status: "scheduled",
  }),
  // 08/31 — Jim Warren — Monthly Express (unpaid)
  computeBookingFormulas({
    id: "aug-9673",
    date: "2026-08-31",
    clientName: "Jim Warren",
    service: "Express Clean",
    serviceCategory: "Monthly",
    frequency: "Monthly",
    city: "Aliso Viejo",
    cleanerTeam: "Juan Romero",
    subTotal: 435,
    salesTax: 0,
    processingFee: 13.05,
    tip: 0,
    teamEarningsWithoutTips: 190,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("4:00"),
    actualHours: parseDuration("4:00"),
    bookedBy: "Subscription",
    status: "scheduled",
  }),
  // 08/31 — Jennifer Cassell — Move In/Out (unpaid)
  computeBookingFormulas({
    id: "aug-11591",
    date: "2026-08-31",
    clientName: "Jennifer Cassell",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "San Clemente",
    cleanerTeam: "Blanca Garcia",
    subTotal: 880,
    salesTax: 0,
    processingFee: 26.4,
    tip: 0,
    teamEarningsWithoutTips: 350,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("5:00"),
    actualHours: parseDuration("5:00"),
    bookedBy: "Online Booking",
    status: "scheduled",
  }),
  // 08/31 — Julie Delfs — Move In/Out (unpaid)
  computeBookingFormulas({
    id: "aug-11590",
    date: "2026-08-31",
    clientName: "Julie Delfs",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Long Beach",
    cleanerTeam: "Rosa Calderon",
    subTotal: 535,
    salesTax: 0,
    processingFee: 16.05,
    tip: 0,
    teamEarningsWithoutTips: 260,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: parseDuration("2:45"),
    actualHours: parseDuration("2:45"),
    bookedBy: "Online Booking",
    status: "scheduled",
  }),
];

export const augustCommercialBookings: ServiceBookingRow[] = [
  computeBookingFormulas({
    id: "comm-aug-steripax",
    date: "2026-08-31",
    clientName: "Steripax",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "5x per week",
    city: "Huntington Beach",
    cleanerTeam: "Lucia Portillo",
    subTotal: 2576.00,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 2080.00,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 130,
    actualHours: 130,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "Lucia Portillo (hourly commercial cleanings)",
  }),
  computeBookingFormulas({
    id: "comm-aug-field-ai",
    date: "2026-08-31",
    clientName: "Field AI",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "5x per week",
    city: "Irvine",
    cleanerTeam: "Ana Morales",
    subTotal: 1850.00,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 1150.00,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 36,
    actualHours: 36,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "Ana Morales (trash + full office recurring)",
  }),
  computeBookingFormulas({
    id: "comm-aug-ilg-valencia",
    date: "2026-08-31",
    clientName: "ILG Valencia Office",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "3x per week",
    city: "Valencia",
    cleanerTeam: "Emmi Guerra",
    subTotal: 1250.00,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 810.00,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 18,
    actualHours: 18,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "Interior Logic Group Valencia (Emmi Guerra)",
  }),
  computeBookingFormulas({
    id: "comm-aug-ilg-irvine",
    date: "2026-08-31",
    clientName: "ILG Irvine Office",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "3x per week",
    city: "Irvine",
    cleanerTeam: "Maria Lopez",
    subTotal: 1200.00,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 768.00,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 16,
    actualHours: 16,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "Interior Logic Group Irvine (Maria Lopez)",
  }),
  computeBookingFormulas({
    id: "comm-aug-ilg-corona",
    date: "2026-08-31",
    clientName: "ILG Corona Office",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "3x per week",
    city: "Corona",
    cleanerTeam: "Sandra Hernandez",
    subTotal: 950.00,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 600.00,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 12,
    actualHours: 12,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "Interior Logic Group Corona (Sandra Hernandez)",
  }),
  computeBookingFormulas({
    id: "comm-aug-13demarzo",
    date: "2026-08-31",
    clientName: "13demarzo",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "2x per week",
    city: "Irvine",
    cleanerTeam: "Sandra Hernandez",
    subTotal: 950.00,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 499.00,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 10,
    actualHours: 10,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "13deMarzo Irvine (Sandra Hernandez)",
  }),
  computeBookingFormulas({
    id: "comm-aug-miracle-minds",
    date: "2026-08-31",
    clientName: "Miracle Minds",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "2x per week",
    city: "Newport",
    cleanerTeam: "Luz Uribe",
    subTotal: 875.00,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 450.00,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 11,
    actualHours: 11,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "Miracle Minds Newport (Luz Uribe)",
  }),
  computeBookingFormulas({
    id: "comm-aug-ilg-westlake",
    date: "2026-08-31",
    clientName: "ILG Westlake",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "3x per week",
    city: "Westlake Village",
    cleanerTeam: "Emmi Guerra",
    subTotal: 850.00,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 540.00,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 10,
    actualHours: 10,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "Interior Logic Group Westlake (Emmi Guerra)",
  }),
  computeBookingFormulas({
    id: "comm-aug-mamas-hb",
    date: "2026-08-31",
    clientName: "Mama's Restaurant HB",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "Weekly (Fri)",
    city: "Huntington Beach",
    cleanerTeam: "Juan Romero",
    subTotal: 800.00,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 360.00,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 16,
    actualHours: 16,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "Mama's Restaurant Huntington Beach (Juan Romero)",
  }),
  computeBookingFormulas({
    id: "comm-aug-globar-medspa",
    date: "2026-08-31",
    clientName: "GLO Bar MedSpa",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "2x per week",
    city: "Costa Mesa",
    cleanerTeam: "Juan Romero",
    subTotal: 725.00,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 360.00,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 12,
    actualHours: 12,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "GLO Bar MedSpa Costa Mesa (Juan Romero)",
  }),
  computeBookingFormulas({
    id: "comm-aug-besst-labs",
    date: "2026-08-31",
    clientName: "Besst Labs",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "Weekly",
    city: "Orange",
    cleanerTeam: "Sandra Hernandez",
    subTotal: 650.00,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 360.00,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 9,
    actualHours: 9,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "Besst Labs Orange (Sandra Hernandez)",
  }),
  computeBookingFormulas({
    id: "comm-aug-macarthur-dental",
    date: "2026-08-31",
    clientName: "MacArthur Dental Arts",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "4x per week",
    city: "Irvine",
    cleanerTeam: "Kassandra Valentin",
    subTotal: 530.00,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 320.00,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 6,
    actualHours: 6,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "MacArthur Dental Arts (Kassandra Valentin)",
  }),
  computeBookingFormulas({
    id: "comm-aug-kott-koatings",
    date: "2026-08-31",
    clientName: "Kott Koatings",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "Weekly",
    city: "Lake Forest",
    cleanerTeam: "Susana Bautista",
    subTotal: 480.00,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 240.00,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 6,
    actualHours: 6,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "Kott Koatings Lake Forest (Susana Bautista)",
  }),
  computeBookingFormulas({
    id: "comm-aug-dr-bagheri",
    date: "2026-08-31",
    clientName: "Dr. Bagheri Office",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "1x per week",
    city: "Irvine",
    cleanerTeam: "Mirna Contreras",
    subTotal: 450.00,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 240.00,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 6,
    actualHours: 6,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "Dr. Bagheri Office Irvine (Mirna Contreras)",
  }),
  computeBookingFormulas({
    id: "comm-aug-kush-fine-art",
    date: "2026-08-31",
    clientName: "Kush Fine Art",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "Every 3 weeks",
    city: "Laguna Beach",
    cleanerTeam: "Sandra Hernandez",
    subTotal: 340.00,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 95.31,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 3,
    actualHours: 3,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "Kush Fine Art Laguna Beach (Sandra Hernandez)",
  }),
  computeBookingFormulas({
    id: "comm-aug-green-leaf",
    date: "2026-08-31",
    clientName: "Green Leaf Botanicals",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "Monthly",
    city: "Whittier",
    cleanerTeam: "Lorena Benitez",
    subTotal: 238.00,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 119.00,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 4,
    actualHours: 4,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "Green Leaf Botanicals Whittier (Lorena Benitez)",
  }),
];

export const augustSalesTrackerBookings: ServiceBookingRow[] = [
  ...augustResidentialBookings,
  ...augustCommercialBookings,
];

