import { computeBookingFormulas } from "./calculator";
import type { ServiceBookingRow } from "./types";

/**
 * SEPTIEMBRE 2026 (RESIDENCIAL — BookingKoala oficial):
 * 50 servicios individuales extraídos del export oficial de BookingKoala.
 * Incluye: Express Clean, Deep Clean, Move In/Out Clean.
 * Cleaners: Miriam Lopez, Rosa Calderon, Blanca Garcia, Juan Romero,
 *           Sofia Diaz, Jasmine Cardenas, Lorena Benitez, Maria Tolentino,
 *           Gabriel Cardenas, Ana Morales.
 */

function freqLabel(f: string): string {
  if (f === "One-Time") return "One Time";
  if (f === "Weekly") return "Weekly";
  if (f === "Every Other Week") return "Biweekly";
  if (f === "Monthly") return "Monthly";
  if (f === "Every 3 Weeks") return "Biweekly";
  return f;
}

export const septemberResidentialBookings: ServiceBookingRow[] = [
  computeBookingFormulas({ id: "sep-11587", date: "2026-09-01", clientName: "Barbara Holbert", service: "Move In/Out Clean", serviceCategory: "Move In/Out Clean", frequency: "One Time", city: "Tustin", cleanerTeam: "Miriam Lopez", subTotal: 415, salesTax: 0, processingFee: 12.45, tip: 0, teamEarningsWithoutTips: 200, merchantFee: 0, stripeFee: 0, durationHours: 2.75, actualHours: 2.75, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-10799", date: "2026-09-01", clientName: "Suneil Agrawal", service: "Express Clean", serviceCategory: "Weekly", frequency: "Weekly", city: "Yorba Linda", cleanerTeam: "Rosa Calderon", subTotal: 530, salesTax: 0, processingFee: 6.72, tip: 0, teamEarningsWithoutTips: 120, merchantFee: 0, stripeFee: 0, durationHours: 2.25, actualHours: 2.25, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11618", date: "2026-09-01", clientName: "Ava Ho", service: "Move In/Out Clean", serviceCategory: "Move In/Out Clean", frequency: "One Time", city: "Irvine", cleanerTeam: "Unassigned", subTotal: 445, salesTax: 0, processingFee: 13.35, tip: 0, teamEarningsWithoutTips: 0, merchantFee: 0, stripeFee: 0, durationHours: 2.75, actualHours: 2.75, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11619", date: "2026-09-02", clientName: "Zach Woody", service: "Deep Clean", serviceCategory: "Deep Clean", frequency: "One Time", city: "Santa Ana", cleanerTeam: "Blanca Garcia", subTotal: 525, salesTax: 0, processingFee: 20.25, tip: 0, teamEarningsWithoutTips: 330, merchantFee: 0, stripeFee: 0, durationHours: 3.25, actualHours: 3.25, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11611", date: "2026-09-02", clientName: "Bill Krause", service: "Deep Clean", serviceCategory: "Deep Clean", frequency: "One Time", city: "Laguna Niguel", cleanerTeam: "Juan Romero", subTotal: 555, salesTax: 0, processingFee: 16.65, tip: 0, teamEarningsWithoutTips: 220, merchantFee: 0, stripeFee: 0, durationHours: 3.5, actualHours: 3.5, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11592", date: "2026-09-03", clientName: "Leslie Feinsilver", service: "Move In/Out Clean", serviceCategory: "Move In/Out Clean", frequency: "One Time", city: "Newport Beach", cleanerTeam: "Sofia Diaz", subTotal: 1278, salesTax: 0, processingFee: 38.34, tip: 0, teamEarningsWithoutTips: 490, merchantFee: 0, stripeFee: 0, durationHours: 4.0, actualHours: 4.0, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-10371", date: "2026-09-04", clientName: "Luann Vance", service: "Express Clean", serviceCategory: "Monthly", frequency: "Monthly", city: "Anaheim", cleanerTeam: "Jasmine Cardenas", subTotal: 335, salesTax: 0, processingFee: 10.05, tip: 0, teamEarningsWithoutTips: 150, merchantFee: 0, stripeFee: 0, durationHours: 2.75, actualHours: 2.75, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11612", date: "2026-09-05", clientName: "Britt Cottrill", service: "Express Clean", serviceCategory: "Standard Clean", frequency: "One Time", city: "Newport Beach", cleanerTeam: "Juan Romero", subTotal: 560, salesTax: 0, processingFee: 27.75, tip: 0, teamEarningsWithoutTips: 500, merchantFee: 0, stripeFee: 0, durationHours: 6.0, actualHours: 6.0, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-10284", date: "2026-09-07", clientName: "Gavriella Youngs", service: "Express Clean", serviceCategory: "Biweekly", frequency: "Biweekly", city: "Rancho Santa Margarita", cleanerTeam: "Unassigned", subTotal: 335, salesTax: 0, processingFee: 6.60, tip: 0, teamEarningsWithoutTips: 0, merchantFee: 0, stripeFee: 0, durationHours: 2.75, actualHours: 2.75, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11594", date: "2026-09-07", clientName: "Linda Matias", service: "Express Clean", serviceCategory: "Standard Clean", frequency: "One Time", city: "Laguna Beach", cleanerTeam: "Blanca Garcia", subTotal: 275, salesTax: 0, processingFee: 4.05, tip: 0, teamEarningsWithoutTips: 120, merchantFee: 0, stripeFee: 0, durationHours: 2.25, actualHours: 2.25, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-10847", date: "2026-09-08", clientName: "Suneil Agrawal", service: "Express Clean", serviceCategory: "Weekly", frequency: "Weekly", city: "Yorba Linda", cleanerTeam: "Rosa Calderon", subTotal: 530, salesTax: 0, processingFee: 6.72, tip: 0, teamEarningsWithoutTips: 120, merchantFee: 0, stripeFee: 0, durationHours: 2.25, actualHours: 2.25, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-10291", date: "2026-09-09", clientName: "Takeo Fujimoto", service: "Express Clean", serviceCategory: "Biweekly", frequency: "Biweekly", city: "Irvine", cleanerTeam: "Lorena Benitez", subTotal: 195, salesTax: 0, processingFee: 4.68, tip: 0, teamEarningsWithoutTips: 78, merchantFee: 0, stripeFee: 0, durationHours: 2.0, actualHours: 2.0, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11627", date: "2026-09-09", clientName: "Britt Cottrill", service: "Express Clean", serviceCategory: "Standard Clean", frequency: "One Time", city: "Newport Beach", cleanerTeam: "Juan Romero", subTotal: 560, salesTax: 0, processingFee: 17.25, tip: 0, teamEarningsWithoutTips: 300, merchantFee: 0, stripeFee: 0, durationHours: 6.0, actualHours: 6.0, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-10322", date: "2026-09-10", clientName: "Grace Lawler", service: "Express Clean", serviceCategory: "Biweekly", frequency: "Biweekly", city: "Irvine", cleanerTeam: "Juan Romero", subTotal: 315, salesTax: 0, processingFee: 7.50, tip: 0, teamEarningsWithoutTips: 170, merchantFee: 0, stripeFee: 0, durationHours: 2.75, actualHours: 2.75, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-10372", date: "2026-09-11", clientName: "Kari Kangas", service: "Express Clean", serviceCategory: "Biweekly", frequency: "Biweekly", city: "Laguna Niguel", cleanerTeam: "Juan Romero", subTotal: 415, salesTax: 0, processingFee: 8.55, tip: 0, teamEarningsWithoutTips: 140, merchantFee: 0, stripeFee: 0, durationHours: 4.0, actualHours: 4.0, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11632", date: "2026-09-11", clientName: "Fouad Habib", service: "Deep Clean", serviceCategory: "Deep Clean", frequency: "One Time", city: "Irvine", cleanerTeam: "Maria Tolentino", subTotal: 390, salesTax: 0, processingFee: 11.70, tip: 0, teamEarningsWithoutTips: 175, merchantFee: 0, stripeFee: 0, durationHours: 2.25, actualHours: 2.25, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11634", date: "2026-09-11", clientName: "Jeremy Wayland", service: "Express Clean", serviceCategory: "Standard Clean", frequency: "One Time", city: "Orange", cleanerTeam: "Juan Romero", subTotal: 560, salesTax: 0, processingFee: 16.80, tip: 0, teamEarningsWithoutTips: 200, merchantFee: 0, stripeFee: 0, durationHours: 2.0, actualHours: 2.0, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11621", date: "2026-09-12", clientName: "Miki Stokes", service: "Express Clean", serviceCategory: "Standard Clean", frequency: "One Time", city: "Ladera Ranch", cleanerTeam: "Gabriel Cardenas", subTotal: 195, salesTax: 0, processingFee: 0, tip: 0, teamEarningsWithoutTips: 170, merchantFee: 0, stripeFee: 0, durationHours: 2.0, actualHours: 2.0, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11638", date: "2026-09-13", clientName: "John Kim", service: "Move In/Out Clean", serviceCategory: "Move In/Out Clean", frequency: "One Time", city: "Irvine", cleanerTeam: "Unassigned", subTotal: 509, salesTax: 0, processingFee: 16.77, tip: 0, teamEarningsWithoutTips: 0, merchantFee: 0, stripeFee: 0, durationHours: 3.0, actualHours: 3.0, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11625", date: "2026-09-13", clientName: "Linda Matias", service: "Express Clean", serviceCategory: "Standard Clean", frequency: "One Time", city: "Laguna Beach", cleanerTeam: "Unassigned", subTotal: 275, salesTax: 0, processingFee: 4.05, tip: 0, teamEarningsWithoutTips: 0, merchantFee: 0, stripeFee: 0, durationHours: 2.25, actualHours: 2.25, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11312", date: "2026-09-14", clientName: "Miki Stokes", service: "Express Clean", serviceCategory: "Weekly", frequency: "Weekly", city: "Ladera Ranch", cleanerTeam: "Juan Romero", subTotal: 680, salesTax: 0, processingFee: 0, tip: 0, teamEarningsWithoutTips: 310, merchantFee: 0, stripeFee: 0, durationHours: 5.5, actualHours: 5.5, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-10964", date: "2026-09-15", clientName: "Suneil Agrawal", service: "Express Clean", serviceCategory: "Weekly", frequency: "Weekly", city: "Yorba Linda", cleanerTeam: "Rosa Calderon", subTotal: 530, salesTax: 0, processingFee: 6.72, tip: 0, teamEarningsWithoutTips: 120, merchantFee: 0, stripeFee: 0, durationHours: 2.25, actualHours: 2.25, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11643", date: "2026-09-16", clientName: "Bertina Chian", service: "Deep Clean", serviceCategory: "Deep Clean", frequency: "One Time", city: "Irvine", cleanerTeam: "Lorena Benitez", subTotal: 330, salesTax: 0, processingFee: 9.90, tip: 0, teamEarningsWithoutTips: 130, merchantFee: 0, stripeFee: 0, durationHours: 6.0, actualHours: 6.0, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11648", date: "2026-09-18", clientName: "Farzana Naz", service: "Move In/Out Clean", serviceCategory: "Move In/Out Clean", frequency: "One Time", city: "Irvine", cleanerTeam: "Lorena Benitez", subTotal: 315, salesTax: 0, processingFee: 0, tip: 0, teamEarningsWithoutTips: 125, merchantFee: 0, stripeFee: 0, durationHours: 2.5, actualHours: 2.5, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-10423", date: "2026-09-18", clientName: "Katarzyna Mcnaughton", service: "Express Clean", serviceCategory: "Biweekly", frequency: "Biweekly", city: "Irvine", cleanerTeam: "Lorena Benitez", subTotal: 385, salesTax: 0, processingFee: 9.24, tip: 0, teamEarningsWithoutTips: 154, merchantFee: 0, stripeFee: 0, durationHours: 4.0, actualHours: 4.0, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11639", date: "2026-09-18", clientName: "Sean Smith", service: "Express Clean", serviceCategory: "Standard Clean", frequency: "One Time", city: "Costa Mesa", cleanerTeam: "Miriam Lopez", subTotal: 125, salesTax: 0, processingFee: 6.30, tip: 0, teamEarningsWithoutTips: 90, merchantFee: 0, stripeFee: 0, durationHours: 2.5, actualHours: 2.5, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11651", date: "2026-09-20", clientName: "Muhammad Almanie", service: "Move In/Out Clean", serviceCategory: "Move In/Out Clean", frequency: "One Time", city: "Irvine", cleanerTeam: "Sofia Diaz", subTotal: 385, salesTax: 0, processingFee: 11.55, tip: 0, teamEarningsWithoutTips: 170, merchantFee: 0, stripeFee: 0, durationHours: 2.5, actualHours: 2.5, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11646", date: "2026-09-20", clientName: "Renewable Farms", service: "Express Clean", serviceCategory: "Standard Clean", frequency: "One Time", city: "Aliso Viejo", cleanerTeam: "Ana Morales", subTotal: 195, salesTax: 0, processingFee: 3.60, tip: 0, teamEarningsWithoutTips: 0, merchantFee: 0, stripeFee: 0, durationHours: 2.0, actualHours: 2.0, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-10285", date: "2026-09-21", clientName: "Gavriella Youngs", service: "Express Clean", serviceCategory: "Biweekly", frequency: "Biweekly", city: "Rancho Santa Margarita", cleanerTeam: "Unassigned", subTotal: 335, salesTax: 0, processingFee: 6.60, tip: 0, teamEarningsWithoutTips: 0, merchantFee: 0, stripeFee: 0, durationHours: 2.75, actualHours: 2.75, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11411", date: "2026-09-21", clientName: "Miki Stokes", service: "Express Clean", serviceCategory: "Weekly", frequency: "Weekly", city: "Ladera Ranch", cleanerTeam: "Juan Romero", subTotal: 680, salesTax: 0, processingFee: 0, tip: 0, teamEarningsWithoutTips: 310, merchantFee: 0, stripeFee: 0, durationHours: 5.5, actualHours: 5.5, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-10573", date: "2026-09-21", clientName: "Lindsay Mullen", service: "Express Clean", serviceCategory: "Biweekly", frequency: "Biweekly", city: "Fullerton", cleanerTeam: "Gabriel Cardenas", subTotal: 275, salesTax: 0, processingFee: 11.25, tip: 0, teamEarningsWithoutTips: 170, merchantFee: 0, stripeFee: 0, durationHours: 2.25, actualHours: 2.25, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-10984", date: "2026-09-22", clientName: "Suneil Agrawal", service: "Express Clean", serviceCategory: "Weekly", frequency: "Weekly", city: "Yorba Linda", cleanerTeam: "Rosa Calderon", subTotal: 530, salesTax: 0, processingFee: 11.52, tip: 0, teamEarningsWithoutTips: 220, merchantFee: 0, stripeFee: 0, durationHours: 2.25, actualHours: 2.25, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11652", date: "2026-09-22", clientName: "Tariq Almani", service: "Move In/Out Clean", serviceCategory: "Move In/Out Clean", frequency: "One Time", city: "Irvine", cleanerTeam: "Sofia Diaz", subTotal: 450, salesTax: 0, processingFee: 13.50, tip: 0, teamEarningsWithoutTips: 210, merchantFee: 0, stripeFee: 0, durationHours: 3.5, actualHours: 3.5, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11654", date: "2026-09-23", clientName: "Britt Cottrill", service: "Deep Clean", serviceCategory: "Deep Clean", frequency: "One Time", city: "Newport Beach", cleanerTeam: "Sofia Diaz", subTotal: 560, salesTax: 0, processingFee: 17.25, tip: 0, teamEarningsWithoutTips: 300, merchantFee: 0, stripeFee: 0, durationHours: 7.0, actualHours: 7.0, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11661", date: "2026-09-23", clientName: "Jenny Kim", service: "Deep Clean", serviceCategory: "Deep Clean", frequency: "One Time", city: "Fullerton", cleanerTeam: "Maria Tolentino", subTotal: 475, salesTax: 0, processingFee: 14.25, tip: 0, teamEarningsWithoutTips: 200, merchantFee: 0, stripeFee: 0, durationHours: 3.5, actualHours: 3.5, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11665", date: "2026-09-23", clientName: "Bill Krause", service: "Express Clean", serviceCategory: "Standard Clean", frequency: "One Time", city: "Laguna Niguel", cleanerTeam: "Maria Tolentino", subTotal: 435, salesTax: 0, processingFee: 12.45, tip: 0, teamEarningsWithoutTips: 190, merchantFee: 0, stripeFee: 0, durationHours: 4.0, actualHours: 4.0, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11670", date: "2026-09-23", clientName: "Jeremy Wayland", service: "Move In/Out Clean", serviceCategory: "Move In/Out Clean", frequency: "One Time", city: "Garden Grove", cleanerTeam: "Sofia Diaz", subTotal: 385, salesTax: 0, processingFee: 0, tip: 0, teamEarningsWithoutTips: 175, merchantFee: 0, stripeFee: 0, durationHours: 2.75, actualHours: 2.75, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-10422", date: "2026-09-24", clientName: "Grace Lawler", service: "Express Clean", serviceCategory: "Biweekly", frequency: "Biweekly", city: "Irvine", cleanerTeam: "Juan Romero", subTotal: 315, salesTax: 0, processingFee: 7.50, tip: 0, teamEarningsWithoutTips: 170, merchantFee: 0, stripeFee: 0, durationHours: 2.75, actualHours: 2.75, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-10489", date: "2026-09-25", clientName: "Kari Kangas", service: "Express Clean", serviceCategory: "Biweekly", frequency: "Biweekly", city: "Laguna Niguel", cleanerTeam: "Juan Romero", subTotal: 415, salesTax: 0, processingFee: 8.55, tip: 0, teamEarningsWithoutTips: 140, merchantFee: 0, stripeFee: 0, durationHours: 4.0, actualHours: 4.0, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11672", date: "2026-09-25", clientName: "Dana Silva", service: "Deep Clean", serviceCategory: "Deep Clean", frequency: "One Time", city: "Garden Grove", cleanerTeam: "Gabriel Cardenas", subTotal: 670, salesTax: 0, processingFee: 20.10, tip: 0, teamEarningsWithoutTips: 350, merchantFee: 0, stripeFee: 0, durationHours: 2.75, actualHours: 2.75, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11660", date: "2026-09-25", clientName: "Holly Geber", service: "Move In/Out Clean", serviceCategory: "Move In/Out Clean", frequency: "One Time", city: "Seal Beach", cleanerTeam: "Sofia Diaz", subTotal: 415, salesTax: 0, processingFee: 12.45, tip: 0, teamEarningsWithoutTips: 285, merchantFee: 0, stripeFee: 0, durationHours: 2.75, actualHours: 2.75, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11647", date: "2026-09-26", clientName: "Jazmine Torres", service: "Move In/Out Clean", serviceCategory: "Move In/Out Clean", frequency: "One Time", city: "Brea", cleanerTeam: "Miriam Lopez", subTotal: 289, salesTax: 0, processingFee: 8.67, tip: 0, teamEarningsWithoutTips: 115, merchantFee: 0, stripeFee: 0, durationHours: 2.5, actualHours: 2.5, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11658", date: "2026-09-26", clientName: "Jon Cousens", service: "Move In/Out Clean", serviceCategory: "Move In/Out Clean", frequency: "One Time", city: "Laguna Woods", cleanerTeam: "Unassigned", subTotal: 319, salesTax: 0, processingFee: 9.57, tip: 0, teamEarningsWithoutTips: 0, merchantFee: 0, stripeFee: 0, durationHours: 2.5, actualHours: 2.5, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11680", date: "2026-09-26", clientName: "Fari Banimahd", service: "Move In/Out Clean", serviceCategory: "Move In/Out Clean", frequency: "One Time", city: "Irvine", cleanerTeam: "Unassigned", subTotal: 385, salesTax: 0, processingFee: 11.55, tip: 0, teamEarningsWithoutTips: 0, merchantFee: 0, stripeFee: 0, durationHours: 2.75, actualHours: 2.75, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-9969",  date: "2026-09-28", clientName: "Jim Warren", service: "Express Clean", serviceCategory: "Monthly", frequency: "Monthly", city: "Aliso Viejo", cleanerTeam: "Juan Romero", subTotal: 435, salesTax: 0, processingFee: 13.05, tip: 0, teamEarningsWithoutTips: 190, merchantFee: 0, stripeFee: 0, durationHours: 4.0, actualHours: 4.0, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11683", date: "2026-09-28", clientName: "Jenny Gutierrez", service: "Move In/Out Clean", serviceCategory: "Move In/Out Clean", frequency: "One Time", city: "Santa Ana", cleanerTeam: "Maria Tolentino", subTotal: 319, salesTax: 0, processingFee: 9.57, tip: 0, teamEarningsWithoutTips: 140, merchantFee: 0, stripeFee: 0, durationHours: 2.5, actualHours: 2.5, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-10985", date: "2026-09-29", clientName: "Suneil Agrawal", service: "Express Clean", serviceCategory: "Weekly", frequency: "Weekly", city: "Yorba Linda", cleanerTeam: "Rosa Calderon", subTotal: 530, salesTax: 0, processingFee: 6.72, tip: 0, teamEarningsWithoutTips: 120, merchantFee: 0, stripeFee: 0, durationHours: 2.25, actualHours: 2.25, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11659", date: "2026-09-29", clientName: "Rajat Chand", service: "Deep Clean", serviceCategory: "Deep Clean", frequency: "One Time", city: "Dana Point", cleanerTeam: "Maria Tolentino", subTotal: 390, salesTax: 0, processingFee: 17.10, tip: 0, teamEarningsWithoutTips: 255, merchantFee: 0, stripeFee: 0, durationHours: 2.75, actualHours: 2.75, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11687", date: "2026-09-29", clientName: "Joyce Rux", service: "Deep Clean", serviceCategory: "Deep Clean", frequency: "One Time", city: "Long Beach", cleanerTeam: "Lorena Benitez", subTotal: 319, salesTax: 0, processingFee: 9.57, tip: 0, teamEarningsWithoutTips: 135, merchantFee: 0, stripeFee: 0, durationHours: 2.0, actualHours: 2.0, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11685", date: "2026-09-29", clientName: "Jeremy Wayland", service: "Move In/Out Clean", serviceCategory: "Move In/Out Clean", frequency: "One Time", city: "Orange", cleanerTeam: "Sofia Diaz", subTotal: 375, salesTax: 0, processingFee: 0, tip: 0, teamEarningsWithoutTips: 190, merchantFee: 0, stripeFee: 0, durationHours: 2.75, actualHours: 2.75, bookedBy: "Online Booking", status: "completed" }),
  computeBookingFormulas({ id: "sep-11522", date: "2026-09-30", clientName: "Miki Stokes", service: "Express Clean", serviceCategory: "Weekly", frequency: "Weekly", city: "Ladera Ranch", cleanerTeam: "Juan Romero", subTotal: 680, salesTax: 0, processingFee: 0, tip: 0, teamEarningsWithoutTips: 310, merchantFee: 0, stripeFee: 0, durationHours: 5.5, actualHours: 5.5, bookedBy: "Online Booking", status: "completed" }),
];

export const septemberSalesTrackerBookings: ServiceBookingRow[] = [
  ...septemberResidentialBookings,
];
