import { computeBookingFormulas } from "./calculator";
import type { ServiceBookingRow } from "./types";

export const initialSalesTrackerBookings: ServiceBookingRow[] = [
  // Commercial Accounts
  computeBookingFormulas({
    id: "comm-steripax-01",
    date: "2026-07-01",
    clientName: "Steripax",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "5 days a week",
    city: "Huntington Beach",
    cleanerTeam: "Lucia Portillo",
    subTotal: 251.36,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 144.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 6.0,
    actualHours: 6.0,
    bookedBy: "Commercial Contract",
  }),
  computeBookingFormulas({
    id: "comm-ilg-westlake-01",
    date: "2026-07-01",
    clientName: "Interior Logic Group, Westlake",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "3 times per week",
    city: "Westlake Village",
    cleanerTeam: "Emmi Guerra",
    subTotal: 86.92,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 57.5,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.5,
    actualHours: 2.5,
    bookedBy: "Commercial Contract",
  }),
  computeBookingFormulas({
    id: "comm-ilg-valencia-01",
    date: "2026-07-01",
    clientName: "Interior Logic Group, Valencia",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "3 times per week",
    city: "Valencia",
    cleanerTeam: "Emmi Guerra",
    subTotal: 157.50,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 103.5,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 4.5,
    actualHours: 4.5,
    bookedBy: "Commercial Contract",
  }),
  computeBookingFormulas({
    id: "comm-ilg-corona-01",
    date: "2026-07-01",
    clientName: "Interior Logic Group, Corona",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "3 times per week",
    city: "Corona",
    cleanerTeam: "Sandra Hernandez",
    subTotal: 86.46,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 69.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 3.0,
    actualHours: 3.0,
    bookedBy: "Commercial Contract",
  }),
  computeBookingFormulas({
    id: "comm-ilg-irvine-01",
    date: "2026-07-01",
    clientName: "Interior Logic Group, Irvine",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "3 times per week",
    city: "Irvine",
    cleanerTeam: "Maria Lopez",
    subTotal: 138.46,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 88.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 4.0,
    actualHours: 4.0,
    bookedBy: "Commercial Contract",
  }),
  computeBookingFormulas({
    id: "comm-field-ai-01",
    date: "2026-07-02",
    clientName: "Field AI",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "5x per week",
    city: "Irvine",
    cleanerTeam: "Ana Morales",
    subTotal: 587.50,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 373.50,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 6.0,
    actualHours: 6.0,
    bookedBy: "Commercial Contract",
  }),
  computeBookingFormulas({
    id: "comm-888-on-main-01",
    date: "2026-07-02",
    clientName: "888 On Main",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "5x per week",
    city: "Santa Ana",
    cleanerTeam: "Ana Morales",
    subTotal: 1165.0,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 920.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 8.0,
    actualHours: 8.0,
    bookedBy: "Commercial Contract",
  }),
  computeBookingFormulas({
    id: "comm-13demarzo-01",
    date: "2026-07-03",
    clientName: "13demarzo",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "5x per week",
    city: "Irvine",
    cleanerTeam: "Sandra Hernandez",
    subTotal: 356.50,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 249.25,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.0,
    actualHours: 2.0,
    bookedBy: "Commercial Contract",
  }),

  // Weekly Recurring
  computeBookingFormulas({
    id: "rec-suneil-agrawal-01",
    date: "2026-07-07",
    clientName: "Suneil Agrawal",
    service: "Express Cleaning/Bathroom",
    serviceCategory: "Weekly",
    frequency: "Weekly",
    city: "Yorba Linda",
    cleanerTeam: "Rosa Calderon",
    subTotal: 224.0,
    salesTax: 6.72,
    tip: 0,
    teamEarningsWithoutTips: 120.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.25,
    actualHours: 2.25,
    bookedBy: "Subscription",
  }),
  computeBookingFormulas({
    id: "rec-suneil-agrawal-02",
    date: "2026-07-16",
    clientName: "Suneil Agrawal",
    service: "Express Cleaning/Bathroom",
    serviceCategory: "Weekly",
    frequency: "Weekly",
    city: "Yorba Linda",
    cleanerTeam: "Rosa Calderon",
    subTotal: 224.0,
    salesTax: 6.72,
    tip: 0,
    teamEarningsWithoutTips: 120.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.25,
    actualHours: 2.25,
    bookedBy: "Subscription",
  }),
  computeBookingFormulas({
    id: "rec-miki-stokes-01",
    date: "2026-07-08",
    clientName: "Miki Stokes",
    service: "Express Cleaning/Bathroom",
    serviceCategory: "Weekly",
    frequency: "Weekly",
    city: "Ladera Ranch",
    cleanerTeam: "Juan Romero",
    subTotal: 690.0,
    salesTax: 0,
    tip: 40.0,
    teamEarningsWithoutTips: 310.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 7.0,
    actualHours: 7.0,
    bookedBy: "Subscription",
  }),

  // Biweekly
  computeBookingFormulas({
    id: "rec-grace-lawler-01",
    date: "2026-07-09",
    clientName: "Grace Lawler",
    service: "Express Cleaning/Bathroom",
    serviceCategory: "Biweekly",
    frequency: "Every 2 weeks",
    city: "Newport Beach",
    cleanerTeam: "Juan Romero",
    subTotal: 250.0,
    salesTax: 7.50,
    tip: 0,
    teamEarningsWithoutTips: 130.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.25,
    actualHours: 2.25,
    bookedBy: "Subscription",
  }),
  computeBookingFormulas({
    id: "rec-katarzyna-01",
    date: "2026-07-02",
    clientName: "Katarzyna Mcnaughton",
    service: "Express Cleaning/Bathroom",
    serviceCategory: "Biweekly",
    frequency: "Every 2 weeks",
    city: "Irvine",
    cleanerTeam: "Lorena Benitez",
    subTotal: 308.0,
    salesTax: 9.24,
    tip: 0,
    teamEarningsWithoutTips: 155.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.25,
    actualHours: 2.25,
    bookedBy: "Subscription",
  }),

  // Triweekly & Monthly
  computeBookingFormulas({
    id: "rec-rachel-armenta-01",
    date: "2026-07-10",
    clientName: "Rachel Armenta",
    service: "Express Cleaning",
    serviceCategory: "Triweekly",
    frequency: "Tri Weekly",
    city: "Corona Del Mar",
    cleanerTeam: "Rosa Calderon",
    subTotal: 332.0,
    salesTax: 9.96,
    tip: 0,
    teamEarningsWithoutTips: 190.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 4.0,
    actualHours: 4.0,
    bookedBy: "Subscription",
  }),
  computeBookingFormulas({
    id: "rec-luann-vance-01",
    date: "2026-07-15",
    clientName: "Luann Vance",
    service: "Deep Clean",
    serviceCategory: "Monthly",
    frequency: "Monthly",
    city: "Orange",
    cleanerTeam: "Jasmine Cardenas",
    subTotal: 335.0,
    salesTax: 10.05,
    tip: 0,
    teamEarningsWithoutTips: 150.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 3.0,
    actualHours: 3.0,
    bookedBy: "Subscription",
  }),
  computeBookingFormulas({
    id: "rec-jim-warren-01",
    date: "2026-07-27",
    clientName: "Jim Warren",
    service: "Deep Clean",
    serviceCategory: "Monthly",
    frequency: "Monthly",
    city: "Orange",
    cleanerTeam: "Juan Romero",
    subTotal: 435.0,
    salesTax: 13.05,
    tip: 0,
    teamEarningsWithoutTips: 190.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 4.0,
    actualHours: 3.0,
    bookedBy: "Subscription",
  }),

  // Deep Clean One-Time
  computeBookingFormulas({
    id: "deep-dave-sparkman-01",
    date: "2026-07-03",
    clientName: "Dave Sparkman",
    service: "Deep Clean",
    serviceCategory: "Deep Clean",
    frequency: "One Time",
    city: "Irvine",
    cleanerTeam: "Lorena Benitez",
    subTotal: 450.0,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 180.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.0,
    actualHours: 2.0,
    bookedBy: "Online Booking",
  }),
  computeBookingFormulas({
    id: "deep-karine-diovani-01",
    date: "2026-07-10",
    clientName: "Karine Diovani",
    service: "Deep Clean",
    serviceCategory: "Deep Clean",
    frequency: "One Time",
    city: "Irvine",
    cleanerTeam: "Dovissy Calderon",
    subTotal: 520.0,
    salesTax: 15.60,
    tip: 0,
    teamEarningsWithoutTips: 250.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.0,
    actualHours: 2.0,
    bookedBy: "Online Booking",
  }),
  computeBookingFormulas({
    id: "deep-victoria-madrid-01",
    date: "2026-07-13",
    clientName: "Victoria Madrid",
    service: "Deep Clean",
    serviceCategory: "Deep Clean",
    frequency: "One Time",
    city: "Aliso Viejo",
    cleanerTeam: "Dovissy Calderon",
    subTotal: 270.0,
    salesTax: 8.10,
    tip: 0,
    teamEarningsWithoutTips: 110.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 1.25,
    actualHours: 1.25,
    bookedBy: "Online Booking",
  }),
  computeBookingFormulas({
    id: "deep-tony-salvo-01",
    date: "2026-07-18",
    clientName: "Tony Salvo",
    service: "Deep Clean",
    serviceCategory: "Deep Clean",
    frequency: "One Time",
    city: "Aliso Viejo",
    cleanerTeam: "Miriam Lopez",
    subTotal: 410.0,
    salesTax: 12.30,
    tip: 0,
    teamEarningsWithoutTips: 160.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 1.25,
    actualHours: 1.25,
    bookedBy: "Online Booking",
  }),

  // Move In/Out Clean
  computeBookingFormulas({
    id: "move-jeremy-wayland-01",
    date: "2026-07-03",
    clientName: "Jeremy Wayland",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Orange",
    cleanerTeam: "Rosa Calderon",
    subTotal: 415.0,
    salesTax: 0,
    tip: 0,
    teamEarningsWithoutTips: 180.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 8.0,
    actualHours: 8.0,
    bookedBy: "Online Booking",
  }),
  computeBookingFormulas({
    id: "move-nikhil-g-01",
    date: "2026-07-03",
    clientName: "Nikhil G",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Huntington Beach",
    cleanerTeam: "Gabriel Cardenas",
    subTotal: 500.0,
    salesTax: 15.00,
    tip: 0,
    teamEarningsWithoutTips: 200.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 3.5,
    actualHours: 3.5,
    bookedBy: "Online Booking",
  }),
  computeBookingFormulas({
    id: "move-marshall-manafian-01",
    date: "2026-07-04",
    clientName: "Marshall Manafian",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Huntington Beach",
    cleanerTeam: "Sofia Diaz",
    subTotal: 385.0,
    salesTax: 11.55,
    tip: 0,
    teamEarningsWithoutTips: 155.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 3.5,
    actualHours: 3.5,
    bookedBy: "Online Booking",
  }),
  computeBookingFormulas({
    id: "move-allison-korkmaz-01",
    date: "2026-07-05",
    clientName: "Allison Korkmaz",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Orange",
    cleanerTeam: "Gabriel Cardenas",
    subTotal: 300.0,
    salesTax: 9.00,
    tip: 0,
    teamEarningsWithoutTips: 120.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 8.0,
    actualHours: 8.0,
    bookedBy: "Online Booking",
  }),
  computeBookingFormulas({
    id: "move-bree-tincopa-01",
    date: "2026-07-06",
    clientName: "Bree Tincopa",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Huntington Beach",
    cleanerTeam: "Gabriel Cardenas",
    subTotal: 375.0,
    salesTax: 11.25,
    tip: 0,
    teamEarningsWithoutTips: 150.0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 3.5,
    actualHours: 3.5,
    bookedBy: "Online Booking",
  }),
];
