import { computeBookingFormulas } from "./calculator";
import type { ServiceBookingRow } from "./types";

/**
 * AGOSTO 2026 (CERRADO Y AUDITADO):
 * 1. Residencial: 55 servicios individuales extraídos del archivo oficial Booking Koala.
 * 2. Comercial: 31 cuentas y contratos comerciales activos extraídos de las capturas con horarios, frecuencias y tarifas exactas de CleanGuru.
 * TOTAL UNIFICADO: 86 registros (55 BK Residencial + 31 Contratos Comerciales).
 */

export const augustResidentialBookings: ServiceBookingRow[] = [
  // 08/01/2026 — Brian Metcalf — Move In/Out Clean
  computeBookingFormulas({
    id: "aug-11475",
    date: "2026-08-01",
    clientName: "Brian Metcalf",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Newport Beach",
    cleanerTeam: "Maria Lopez",
    subTotal: 590,
    salesTax: 0,
    processingFee: 17.7,
    tip: 0,
    teamEarningsWithoutTips: 350,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 3.5,
    actualHours: 3.5,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/01/2026 — Sonia Kim — Move In/Out Clean
  computeBookingFormulas({
    id: "aug-11479",
    date: "2026-08-01",
    clientName: "Sonia Kim",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Fullerton",
    cleanerTeam: "Miriam Lopez",
    subTotal: 469,
    salesTax: 0,
    processingFee: 14.07,
    tip: 0,
    teamEarningsWithoutTips: 185,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 3,
    actualHours: 3,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/04/2026 — Suneil Agrawal — Weekly
  computeBookingFormulas({
    id: "aug-10650",
    date: "2026-08-04",
    clientName: "Suneil Agrawal",
    service: "Express Clean",
    serviceCategory: "Weekly",
    frequency: "Weekly",
    city: "Yorba Linda",
    cleanerTeam: "Rosa Calderon",
    subTotal: 530,
    salesTax: 0,
    processingFee: 6.72,
    tip: 0,
    teamEarningsWithoutTips: 120,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.25,
    actualHours: 2.25,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/05/2026 — Miki Stokes — Weekly
  computeBookingFormulas({
    id: "aug-11134",
    date: "2026-08-05",
    clientName: "Miki Stokes",
    service: "Express Clean",
    serviceCategory: "Weekly",
    frequency: "Weekly",
    city: "Ladera Ranch",
    cleanerTeam: "Juan Romero",
    subTotal: 680,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 310,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 5.5,
    actualHours: 5.5,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/05/2026 — Takeo Fujimoto — Biweekly
  computeBookingFormulas({
    id: "aug-10117",
    date: "2026-08-05",
    clientName: "Takeo Fujimoto",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Irvine",
    cleanerTeam: "Lorena Benitez",
    subTotal: 195,
    salesTax: 0,
    processingFee: 4.68,
    tip: 0,
    teamEarningsWithoutTips: 78,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2,
    actualHours: 2,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/05/2026 — Rob Catena — Deep Clean
  computeBookingFormulas({
    id: "aug-11465",
    date: "2026-08-05",
    clientName: "Rob Catena",
    service: "Deep Clean",
    serviceCategory: "Deep Clean",
    frequency: "One Time",
    city: "Coto de Caza",
    cleanerTeam: "Miriam Lopez",
    subTotal: 655,
    salesTax: 0,
    processingFee: 19.65,
    tip: 0,
    teamEarningsWithoutTips: 260,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 4,
    actualHours: 4,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/05/2026 — Linda Matias — Standard Clean
  computeBookingFormulas({
    id: "aug-11087",
    date: "2026-08-05",
    clientName: "Linda Matias",
    service: "Express Clean",
    serviceCategory: "Standard Clean",
    frequency: "One Time",
    city: "Laguna Beach",
    cleanerTeam: "Gabriel Cardenas",
    subTotal: 275,
    salesTax: 0,
    processingFee: 4.05,
    tip: 0,
    teamEarningsWithoutTips: 85,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.25,
    actualHours: 2.25,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/06/2026 — Britt Cottrill — Standard Clean
  computeBookingFormulas({
    id: "aug-11612",
    date: "2026-08-06",
    clientName: "Britt Cottrill",
    service: "Express Clean",
    serviceCategory: "Standard Clean",
    frequency: "One Time",
    city: "Newport Beach",
    cleanerTeam: "Juan Romero",
    subTotal: 560,
    salesTax: 0,
    processingFee: 17.25,
    tip: 0,
    teamEarningsWithoutTips: 300,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 6,
    actualHours: 6,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/06/2026 — Kyle Digiantonio — Move In/Out Clean
  computeBookingFormulas({
    id: "aug-11497",
    date: "2026-08-06",
    clientName: "Kyle Digiantonio",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Costa Mesa",
    cleanerTeam: "Dovissy Calderon",
    subTotal: 973.58,
    salesTax: 0,
    processingFee: 29.21,
    tip: 0,
    teamEarningsWithoutTips: 500,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 3.5,
    actualHours: 3.5,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/07/2026 — larry silfen — Biweekly
  computeBookingFormulas({
    id: "aug-11507",
    date: "2026-08-07",
    clientName: "larry silfen",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Ladera Ranch",
    cleanerTeam: "Blanca Garcia",
    subTotal: 300,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 200,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 4.5,
    actualHours: 4.5,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/07/2026 — James Bae — Biweekly
  computeBookingFormulas({
    id: "aug-10542",
    date: "2026-08-07",
    clientName: "James Bae",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Costa Mesa",
    cleanerTeam: "Unassigned",
    subTotal: 188,
    salesTax: 0,
    processingFee: 4.2,
    tip: 0,
    teamEarningsWithoutTips: 0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 0,
    actualHours: 0,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/07/2026 — Lindsay Mullen — Triweekly
  computeBookingFormulas({
    id: "aug-10571",
    date: "2026-08-07",
    clientName: "Lindsay Mullen",
    service: "Express Clean",
    serviceCategory: "Triweekly",
    frequency: "Every 3 Weeks",
    city: "Orange County",
    cleanerTeam: "Gabriel Cardenas",
    subTotal: 275,
    salesTax: 0,
    processingFee: 6.75,
    tip: 0,
    teamEarningsWithoutTips: 120,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.25,
    actualHours: 2.25,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/07/2026 — Shaila Emani — Move In/Out Clean
  computeBookingFormulas({
    id: "aug-11484",
    date: "2026-08-07",
    clientName: "Shaila Emani",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Irvine",
    cleanerTeam: "Miriam Lopez",
    subTotal: 349,
    salesTax: 0,
    processingFee: 10.47,
    tip: 0,
    teamEarningsWithoutTips: 140,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.5,
    actualHours: 2.5,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/07/2026 — Zach Renderos — Biweekly
  computeBookingFormulas({
    id: "aug-11037",
    date: "2026-08-07",
    clientName: "Zach Renderos",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Santa Ana",
    cleanerTeam: "Lorena Benitez",
    subTotal: 275,
    salesTax: 0,
    processingFee: 6.6,
    tip: 0,
    teamEarningsWithoutTips: 100,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.25,
    actualHours: 2.25,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/09/2026 — Tongsu Hong — Move In/Out Clean
  computeBookingFormulas({
    id: "aug-11492",
    date: "2026-08-09",
    clientName: "Tongsu Hong",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Irvine",
    cleanerTeam: "Miriam Lopez",
    subTotal: 319,
    salesTax: 0,
    processingFee: 9.57,
    tip: 0,
    teamEarningsWithoutTips: 125,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.5,
    actualHours: 2.5,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/10/2026 — Suneil Agrawal — Weekly
  computeBookingFormulas({
    id: "aug-10651",
    date: "2026-08-10",
    clientName: "Suneil Agrawal",
    service: "Express Clean",
    serviceCategory: "Weekly",
    frequency: "Weekly",
    city: "Yorba Linda",
    cleanerTeam: "Rosa Calderon",
    subTotal: 530,
    salesTax: 0,
    processingFee: 6.72,
    tip: 0,
    teamEarningsWithoutTips: 120,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.25,
    actualHours: 2.25,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/12/2026 — Britt Cottrill — Standard Clean
  computeBookingFormulas({
    id: "aug-11438",
    date: "2026-08-12",
    clientName: "Britt Cottrill",
    service: "Express Clean",
    serviceCategory: "Standard Clean",
    frequency: "One Time",
    city: "Newport Beach",
    cleanerTeam: "Jasmine Cardenas",
    subTotal: 560,
    salesTax: 0,
    processingFee: 17.25,
    tip: 0,
    teamEarningsWithoutTips: 300,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 6,
    actualHours: 6,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/13/2026 — Grace Lawler — Biweekly
  computeBookingFormulas({
    id: "aug-10143",
    date: "2026-08-13",
    clientName: "Grace Lawler",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Irvine",
    cleanerTeam: "Juan Romero",
    subTotal: 315,
    salesTax: 0,
    processingFee: 7.5,
    tip: 0,
    teamEarningsWithoutTips: 130,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.75,
    actualHours: 2.75,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/14/2026 — Kari Kangas — Biweekly
  computeBookingFormulas({
    id: "aug-10165",
    date: "2026-08-14",
    clientName: "Kari Kangas",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Laguna Niguel",
    cleanerTeam: "Juan Romero",
    subTotal: 415,
    salesTax: 0,
    processingFee: 8.55,
    tip: 0,
    teamEarningsWithoutTips: 140,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 4,
    actualHours: 4,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/14/2026 — Sonya Park — Deep Clean
  computeBookingFormulas({
    id: "aug-11532",
    date: "2026-08-14",
    clientName: "Sonya Park",
    service: "Deep Clean",
    serviceCategory: "Deep Clean",
    frequency: "One Time",
    city: "Irvine",
    cleanerTeam: "Miriam Lopez",
    subTotal: 300,
    salesTax: 0,
    processingFee: 9,
    tip: 0,
    teamEarningsWithoutTips: 120,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2,
    actualHours: 2,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/14/2026 — Rachel Akiyama — Biweekly
  computeBookingFormulas({
    id: "aug-10690",
    date: "2026-08-14",
    clientName: "Rachel Akiyama",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Mission Viejo",
    cleanerTeam: "Unassigned",
    subTotal: 385,
    salesTax: 0,
    processingFee: 12.24,
    tip: 0,
    teamEarningsWithoutTips: 0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.75,
    actualHours: 2.75,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/14/2026 — Katarzyna Mcnaughton — Biweekly
  computeBookingFormulas({
    id: "aug-10227",
    date: "2026-08-14",
    clientName: "Katarzyna Mcnaughton",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Irvine",
    cleanerTeam: "Lorena Benitez",
    subTotal: 385,
    salesTax: 0,
    processingFee: 9.24,
    tip: 0,
    teamEarningsWithoutTips: 154,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 4,
    actualHours: 4,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/16/2026 — Chris Chambers — Move In/Out Clean
  computeBookingFormulas({
    id: "aug-11539",
    date: "2026-08-16",
    clientName: "Chris Chambers",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Fullerton",
    cleanerTeam: "Jasmine Cardenas",
    subTotal: 509,
    salesTax: 0,
    processingFee: 15.27,
    tip: 0,
    teamEarningsWithoutTips: 220,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 3,
    actualHours: 3,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/17/2026 — Linda Matias — Standard Clean
  computeBookingFormulas({
    id: "aug-11397",
    date: "2026-08-17",
    clientName: "Linda Matias",
    service: "Express Clean",
    serviceCategory: "Standard Clean",
    frequency: "One Time",
    city: "Laguna Beach",
    cleanerTeam: "Blanca Garcia",
    subTotal: 275,
    salesTax: 0,
    processingFee: 6.9,
    tip: 0,
    teamEarningsWithoutTips: 180,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.25,
    actualHours: 2.25,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/18/2026 — Stephanie Deluna — Move In/Out Clean
  computeBookingFormulas({
    id: "aug-11541",
    date: "2026-08-18",
    clientName: "Stephanie Deluna",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Whittier",
    cleanerTeam: "Juan Romero",
    subTotal: 395,
    salesTax: 0,
    processingFee: 11.85,
    tip: 0,
    teamEarningsWithoutTips: 197.5,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.75,
    actualHours: 2.75,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/18/2026 — Suneil Agrawal — Weekly
  computeBookingFormulas({
    id: "aug-10721",
    date: "2026-08-18",
    clientName: "Suneil Agrawal",
    service: "Express Clean",
    serviceCategory: "Weekly",
    frequency: "Weekly",
    city: "Yorba Linda",
    cleanerTeam: "Rosa Calderon",
    subTotal: 530,
    salesTax: 0,
    processingFee: 6.72,
    tip: 0,
    teamEarningsWithoutTips: 120,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.25,
    actualHours: 2.25,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/20/2026 — Britt Cottrill — Standard Clean
  computeBookingFormulas({
    id: "aug-11540",
    date: "2026-08-20",
    clientName: "Britt Cottrill",
    service: "Express Clean",
    serviceCategory: "Standard Clean",
    frequency: "One Time",
    city: "Newport Beach",
    cleanerTeam: "Juan Romero",
    subTotal: 560,
    salesTax: 0,
    processingFee: 17.25,
    tip: 0,
    teamEarningsWithoutTips: 300,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 6,
    actualHours: 6,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/20/2026 — Emily Flowers — Move In/Out Clean
  computeBookingFormulas({
    id: "aug-11551",
    date: "2026-08-20",
    clientName: "Emily Flowers",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Irvine",
    cleanerTeam: "Blanca Garcia",
    subTotal: 374,
    salesTax: 0,
    processingFee: 12.72,
    tip: 0,
    teamEarningsWithoutTips: 170,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.75,
    actualHours: 2.75,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/21/2026 — Julianna Sockol — Move In/Out Clean
  computeBookingFormulas({
    id: "aug-11542",
    date: "2026-08-21",
    clientName: "Julianna Sockol",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Orange",
    cleanerTeam: "Lorena Benitez",
    subTotal: 479,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 175,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 3,
    actualHours: 3,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/21/2026 — Zach Renderos — Biweekly
  computeBookingFormulas({
    id: "aug-11038",
    date: "2026-08-21",
    clientName: "Zach Renderos",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Santa Ana",
    cleanerTeam: "Lorena Benitez",
    subTotal: 275,
    salesTax: 0,
    processingFee: 6.6,
    tip: 0,
    teamEarningsWithoutTips: 100,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.25,
    actualHours: 2.25,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/21/2026 — Britt Cottrill — Standard Clean
  computeBookingFormulas({
    id: "aug-11564",
    date: "2026-08-21",
    clientName: "Britt Cottrill",
    service: "Express Clean",
    serviceCategory: "Standard Clean",
    frequency: "One Time",
    city: "Newport Beach",
    cleanerTeam: "Juan Romero",
    subTotal: 560,
    salesTax: 0,
    processingFee: 18.75,
    tip: 0,
    teamEarningsWithoutTips: 300,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 6,
    actualHours: 6,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/21/2026 — Jeremy Wayland — Move In/Out Clean
  computeBookingFormulas({
    id: "aug-11550",
    date: "2026-08-21",
    clientName: "Jeremy Wayland",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Orange",
    cleanerTeam: "Jasmine Cardenas",
    subTotal: 415,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 200,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.75,
    actualHours: 2.75,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/22/2026 — Levi Archuleta — Move In/Out Clean
  computeBookingFormulas({
    id: "aug-11543",
    date: "2026-08-22",
    clientName: "Levi Archuleta",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "San Clemente",
    cleanerTeam: "Unassigned",
    subTotal: 1317,
    salesTax: 0,
    processingFee: 39.51,
    tip: 0,
    teamEarningsWithoutTips: 0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 4,
    actualHours: 4,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/23/2026 — Linda Matias — Standard Clean
  computeBookingFormulas({
    id: "aug-11502",
    date: "2026-08-23",
    clientName: "Linda Matias",
    service: "Express Clean",
    serviceCategory: "Standard Clean",
    frequency: "One Time",
    city: "Laguna Beach",
    cleanerTeam: "Blanca Garcia",
    subTotal: 275,
    salesTax: 0,
    processingFee: 4.05,
    tip: 0,
    teamEarningsWithoutTips: 130,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.25,
    actualHours: 2.25,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/24/2026 — Gavriella Youngs — Biweekly
  computeBookingFormulas({
    id: "aug-10228",
    date: "2026-08-24",
    clientName: "Gavriella Youngs",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Rancho Santa Margarita",
    cleanerTeam: "Unassigned",
    subTotal: 335,
    salesTax: 0,
    processingFee: 6.6,
    tip: 0,
    teamEarningsWithoutTips: 0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.75,
    actualHours: 2.75,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/24/2026 — Britt Cottrill — Standard Clean
  computeBookingFormulas({
    id: "aug-11576",
    date: "2026-08-24",
    clientName: "Britt Cottrill",
    service: "Express Clean",
    serviceCategory: "Standard Clean",
    frequency: "One Time",
    city: "Newport Beach",
    cleanerTeam: "Blanca Garcia",
    subTotal: 560,
    salesTax: 0,
    processingFee: 17.25,
    tip: 0,
    teamEarningsWithoutTips: 300,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 6,
    actualHours: 6,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/25/2026 — Suneil Agrawal — Weekly
  computeBookingFormulas({
    id: "aug-10760",
    date: "2026-08-25",
    clientName: "Suneil Agrawal",
    service: "Express Clean",
    serviceCategory: "Weekly",
    frequency: "Weekly",
    city: "Yorba Linda",
    cleanerTeam: "Rosa Calderon",
    subTotal: 530,
    salesTax: 0,
    processingFee: 6.72,
    tip: 0,
    teamEarningsWithoutTips: 120,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.25,
    actualHours: 2.25,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/25/2026 — Teresa West — Move In/Out Clean
  computeBookingFormulas({
    id: "aug-11536",
    date: "2026-08-25",
    clientName: "Teresa West",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Orange",
    cleanerTeam: "Lorena Benitez",
    subTotal: 289,
    salesTax: 0,
    processingFee: 8.67,
    tip: 0,
    teamEarningsWithoutTips: 115,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.5,
    actualHours: 2.5,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/25/2026 — Chiaka Ogbogu — Move In/Out Clean
  computeBookingFormulas({
    id: "aug-11579",
    date: "2026-08-25",
    clientName: "Chiaka Ogbogu",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Irvine",
    cleanerTeam: "Miriam Lopez",
    subTotal: 345,
    salesTax: 0,
    processingFee: 10.35,
    tip: 0,
    teamEarningsWithoutTips: 130,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.75,
    actualHours: 2.75,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/25/2026 — Britt Cottrill — Standard Clean
  computeBookingFormulas({
    id: "aug-11575",
    date: "2026-08-25",
    clientName: "Britt Cottrill",
    service: "Express Clean",
    serviceCategory: "Standard Clean",
    frequency: "One Time",
    city: "Newport Beach",
    cleanerTeam: "Juan Romero",
    subTotal: 560,
    salesTax: 0,
    processingFee: 17.25,
    tip: 0,
    teamEarningsWithoutTips: 300,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 6,
    actualHours: 6,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/26/2026 — Miki Stokes — Weekly
  computeBookingFormulas({
    id: "aug-11247",
    date: "2026-08-26",
    clientName: "Miki Stokes",
    service: "Express Clean",
    serviceCategory: "Weekly",
    frequency: "Weekly",
    city: "Ladera Ranch",
    cleanerTeam: "Juan Romero",
    subTotal: 680,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 310,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 5.5,
    actualHours: 5.5,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/26/2026 — Takeo Fujimoto — Biweekly
  computeBookingFormulas({
    id: "aug-10195",
    date: "2026-08-26",
    clientName: "Takeo Fujimoto",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Irvine",
    cleanerTeam: "Lorena Benitez",
    subTotal: 195,
    salesTax: 0,
    processingFee: 4.68,
    tip: 0,
    teamEarningsWithoutTips: 78,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2,
    actualHours: 2,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/27/2026 — Allison Korkmaz — Move In/Out Clean
  computeBookingFormulas({
    id: "aug-11578",
    date: "2026-08-27",
    clientName: "Allison Korkmaz",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "San Clemente",
    cleanerTeam: "Blanca Garcia",
    subTotal: 380,
    salesTax: 0,
    processingFee: 11.4,
    tip: 0,
    teamEarningsWithoutTips: 200,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.5,
    actualHours: 2.5,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/27/2026 — Grace Lawler — Biweekly
  computeBookingFormulas({
    id: "aug-10222",
    date: "2026-08-27",
    clientName: "Grace Lawler",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Irvine",
    cleanerTeam: "Juan Romero",
    subTotal: 315,
    salesTax: 0,
    processingFee: 7.5,
    tip: 0,
    teamEarningsWithoutTips: 130,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.75,
    actualHours: 2.75,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/28/2026 — Kari Kangas — Biweekly
  computeBookingFormulas({
    id: "aug-10266",
    date: "2026-08-28",
    clientName: "Kari Kangas",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Laguna Niguel",
    cleanerTeam: "Juan Romero",
    subTotal: 415,
    salesTax: 0,
    processingFee: 8.55,
    tip: 0,
    teamEarningsWithoutTips: 140,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 4,
    actualHours: 4,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/28/2026 — Rachel Akiyama — Biweekly
  computeBookingFormulas({
    id: "aug-10691",
    date: "2026-08-28",
    clientName: "Rachel Akiyama",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Mission Viejo",
    cleanerTeam: "Unassigned",
    subTotal: 385,
    salesTax: 0,
    processingFee: 12.24,
    tip: 0,
    teamEarningsWithoutTips: 0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.75,
    actualHours: 2.75,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/28/2026 — Katarzyna Mcnaughton — Biweekly
  computeBookingFormulas({
    id: "aug-10323",
    date: "2026-08-28",
    clientName: "Katarzyna Mcnaughton",
    service: "Express Clean",
    serviceCategory: "Biweekly",
    frequency: "Every Other Week",
    city: "Irvine",
    cleanerTeam: "Lorena Benitez",
    subTotal: 385,
    salesTax: 0,
    processingFee: 9.24,
    tip: 0,
    teamEarningsWithoutTips: 154,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 4,
    actualHours: 4,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/28/2026 — Lindsay Mullen — Triweekly
  computeBookingFormulas({
    id: "aug-10572",
    date: "2026-08-28",
    clientName: "Lindsay Mullen",
    service: "Express Clean",
    serviceCategory: "Triweekly",
    frequency: "Every 3 Weeks",
    city: "Orange County",
    cleanerTeam: "Gabriel Cardenas",
    subTotal: 275,
    salesTax: 0,
    processingFee: 6.75,
    tip: 0,
    teamEarningsWithoutTips: 120,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.25,
    actualHours: 2.25,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/28/2026 — Linda Matias — Standard Clean
  computeBookingFormulas({
    id: "aug-11405",
    date: "2026-08-28",
    clientName: "Linda Matias",
    service: "Express Clean",
    serviceCategory: "Standard Clean",
    frequency: "One Time",
    city: "Laguna Beach",
    cleanerTeam: "Blanca Garcia",
    subTotal: 275,
    salesTax: 0,
    processingFee: 4.05,
    tip: 0,
    teamEarningsWithoutTips: 120,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.25,
    actualHours: 2.25,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/29/2026 — Keith Delossantos — Deep Clean
  computeBookingFormulas({
    id: "aug-11567",
    date: "2026-08-29",
    clientName: "Keith Delossantos",
    service: "Deep Clean",
    serviceCategory: "Deep Clean",
    frequency: "Monthly",
    city: "Irvine",
    cleanerTeam: "Miriam Lopez",
    subTotal: 230,
    salesTax: 0,
    processingFee: 6.9,
    tip: 0,
    teamEarningsWithoutTips: 90,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2,
    actualHours: 2,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/29/2026 — Ava Phillips — Deep Clean
  computeBookingFormulas({
    id: "aug-11604",
    date: "2026-08-29",
    clientName: "Ava Phillips",
    service: "Deep Clean",
    serviceCategory: "Deep Clean",
    frequency: "One Time",
    city: "Irvine",
    cleanerTeam: "Miriam Lopez",
    subTotal: 260,
    salesTax: 0,
    processingFee: 7.8,
    tip: 0,
    teamEarningsWithoutTips: 105,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2,
    actualHours: 2,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/30/2026 — Bill Krause — Deep Clean
  computeBookingFormulas({
    id: "aug-11611",
    date: "2026-08-30",
    clientName: "Bill Krause",
    service: "Deep Clean",
    serviceCategory: "Deep Clean",
    frequency: "One Time",
    city: "Laguna Niguel",
    cleanerTeam: "Unassigned",
    subTotal: 555,
    salesTax: 0,
    processingFee: 16.65,
    tip: 0,
    teamEarningsWithoutTips: 0,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 3.5,
    actualHours: 3.5,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/31/2026 — Jim Warren — Monthly
  computeBookingFormulas({
    id: "aug-9673",
    date: "2026-08-31",
    clientName: "Jim Warren",
    service: "Express Clean",
    serviceCategory: "Monthly",
    frequency: "Monthly",
    city: "Aliso Viejo",
    cleanerTeam: "Juan Romero",
    subTotal: 435,
    salesTax: 0,
    processingFee: 13.05,
    tip: 0,
    teamEarningsWithoutTips: 190,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 4,
    actualHours: 4,
    bookedBy: "Subscription",
    status: "completed",
  }),
  // 08/31/2026 — Jennifer Cassell — Move In/Out Clean
  computeBookingFormulas({
    id: "aug-11591",
    date: "2026-08-31",
    clientName: "Jennifer Cassell",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "San Clemente",
    cleanerTeam: "Blanca Garcia",
    subTotal: 880,
    salesTax: 0,
    processingFee: 26.4,
    tip: 0,
    teamEarningsWithoutTips: 350,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 5,
    actualHours: 5,
    bookedBy: "Online Booking",
    status: "completed",
  }),
  // 08/31/2026 — Julie Delfs — Move In/Out Clean
  computeBookingFormulas({
    id: "aug-11590",
    date: "2026-08-31",
    clientName: "Julie Delfs",
    service: "Move In/Out Clean",
    serviceCategory: "Move In/Out Clean",
    frequency: "One Time",
    city: "Long Beach",
    cleanerTeam: "Rosa Calderon",
    subTotal: 535,
    salesTax: 0,
    processingFee: 16.05,
    tip: 0,
    teamEarningsWithoutTips: 260,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2.75,
    actualHours: 2.75,
    bookedBy: "Online Booking",
    status: "completed",
  }),
];

export const augustCommercialBookings: ServiceBookingRow[] = [
  // Contrato Comercial: 13demarzo (Sandra Hernandez) — 2x per week
  computeBookingFormulas({
    id: "comm-aug-13demarzo-irvine-31",
    date: "2026-08-31",
    clientName: "13demarzo",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "2x per week",
    city: "Irvine",
    cleanerTeam: "Sandra Hernandez",
    subTotal: 950,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 499,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 22.5,
    actualHours: 22.5,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "9 visitas en agosto (Sandra Hernandez). Horario: Monday 9:00 PM - 10:00 PM; Thursday 9:00 PM - 10:00 PM",
  }),
  // Contrato Comercial: Cornerstone Rehab (Kassandra Valentin) — 3x per week
  computeBookingFormulas({
    id: "comm-aug-cornerstone-southern-california",
    date: "2026-08-31",
    clientName: "Cornerstone Rehab",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "3x per week",
    city: "Santa Ana",
    cleanerTeam: "Kassandra Valentin",
    subTotal: 2850,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 1943.5,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 91,
    actualHours: 91,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "13 visitas en agosto (Kassandra Valentin). Horario: Monday 5:00 PM - 5:00 AM; Wednesday 5:00 PM - 5:00 AM; Friday 5:00 PM - 5:00 AM",
  }),
  // Contrato Comercial: Elevate Aerial Huntington Beach (Luz Uribe) — 1x per week
  computeBookingFormulas({
    id: "comm-aug-elevate-aerial-hb-huntington-beach-22",
    date: "2026-08-31",
    clientName: "Elevate Aerial Huntington Beach",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "1x per week",
    city: "Huntington Beach",
    cleanerTeam: "Luz Uribe",
    subTotal: 800,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 498,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 30,
    actualHours: 30,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "5 visitas en agosto (Luz Uribe). Horario: Sunday (Any time)",
  }),
  // Contrato Comercial: Field AI (Veronica Ladinos) — 5x per week
  computeBookingFormulas({
    id: "comm-aug-field-ai-irvine-30",
    date: "2026-08-31",
    clientName: "Field AI",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "5x per week",
    city: "Irvine",
    cleanerTeam: "Veronica Ladinos",
    subTotal: 3390,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 2093,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 126,
    actualHours: 126,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "21 visitas en agosto (Veronica Ladinos). Horario: Monday 11:58 PM - 4:00 AM; Tuesday 11:58 PM - 4:00 AM; Wednesday 11:58 PM - 4:00 AM; Thursday 11:58 PM - 4:00 AM; Friday 11:58 PM - 4:00 AM",
  }),
  // Contrato Comercial: GLO Bar MedSpa (Juan Romero) — 2x per week
  computeBookingFormulas({
    id: "comm-aug-globar-medspa-costa-mesa-35",
    date: "2026-08-31",
    clientName: "GLO Bar MedSpa",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "2x per week",
    city: "Costa Mesa",
    cleanerTeam: "Juan Romero",
    subTotal: 1450,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 468,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 27,
    actualHours: 27,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "9 visitas en agosto (Juan Romero). Horario: Sunday 6:00 PM - 9:00 AM; Wednesday 6:00 PM - 9:00 AM",
  }),
  // Contrato Comercial: Green Leaf Botanicals (Lorena Benitez) — Monthly
  computeBookingFormulas({
    id: "comm-aug-green-leaf-botanicals-whittier-8",
    date: "2026-08-31",
    clientName: "Green Leaf Botanicals",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "Monthly",
    city: "Whittier",
    cleanerTeam: "Lorena Benitez",
    subTotal: 238,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 119,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 2,
    actualHours: 2,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "1 visitas en agosto (Lorena Benitez). Horario: Monthly service (Lorena 100% residencial)",
  }),
  // Contrato Comercial: ILG Corona Office (Sandra Hernandez) — 3x per week
  computeBookingFormulas({
    id: "comm-aug-ilg-corona-office-corona-19",
    date: "2026-08-31",
    clientName: "ILG Corona Office",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "3x per week",
    city: "Corona",
    cleanerTeam: "Sandra Hernandez",
    subTotal: 1163,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 897,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 39,
    actualHours: 39,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "13 visitas en agosto (Sandra Hernandez). Horario: Monday 5:00 PM - 2:00 AM; Wednesday 5:00 PM - 2:00 AM; Friday 5:00 PM - 2:00 AM",
  }),
  // Contrato Comercial: ILG Irvine Office (Maria Lopez) — 3x per week
  computeBookingFormulas({
    id: "comm-aug-ilg-irvine-office-irvine-18",
    date: "2026-08-31",
    clientName: "ILG Irvine Office",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "3x per week",
    city: "Irvine",
    cleanerTeam: "Maria Lopez",
    subTotal: 1800,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 1196,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 32.5,
    actualHours: 32.5,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "13 visitas en agosto (Maria Lopez). Horario: Monday 5:00 PM - 11:00 PM; Wednesday 5:00 PM - 11:00 PM; Friday 5:00 PM - 11:00 PM",
  }),
  // Contrato Comercial: Interior Logic Group - Valencia Office (Emmi Guerra) — 3x per week
  computeBookingFormulas({
    id: "comm-aug-ilg-valencia-office-valencia-21",
    date: "2026-08-31",
    clientName: "Interior Logic Group - Valencia Office",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "3x per week",
    city: "Valencia",
    cleanerTeam: "Emmi Guerra",
    subTotal: 1890,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 1345.5,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 71.5,
    actualHours: 71.5,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "13 visitas en agosto (Emmi Guerra). Horario: Monday 5:00 PM - 5:00 AM; Wednesday 5:00 PM - 5:00 AM; Friday 5:00 PM - 5:00 AM",
  }),
  // Contrato Comercial: ILG Westlake (Emmi Guerra) — 3x per week
  computeBookingFormulas({
    id: "comm-aug-ilg-westlake-westlake-village-20",
    date: "2026-08-31",
    clientName: "ILG Westlake",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "3x per week",
    city: "Westlake Village",
    cleanerTeam: "Emmi Guerra",
    subTotal: 1130,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 747.5,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 32.5,
    actualHours: 32.5,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "13 visitas en agosto (Emmi Guerra). Horario: Monday 5:00 PM - 5:00 AM; Wednesday 5:00 PM - 5:00 AM; Friday 5:00 PM - 5:00 AM",
  }),
  // Contrato Comercial: Kott Koatings (Unassigned) — 1x per week
  computeBookingFormulas({
    id: "comm-aug-kott-koatings-lake-forest-13",
    date: "2026-08-31",
    clientName: "Kott Koatings",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "1x per week",
    city: "Lake Forest",
    cleanerTeam: "Unassigned",
    subTotal: 606.67,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 299,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 12,
    actualHours: 12,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "4 visitas en agosto (Unassigned). Horario: Wednesday 9:00 AM - 12:00 PM",
  }),
  // Contrato Comercial: Kush Fine Art (Ana Morales) — Every 21 days
  computeBookingFormulas({
    id: "comm-aug-kush-fine-art-laguna-beach-14",
    date: "2026-08-31",
    clientName: "Kush Fine Art",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "Every 21 days",
    city: "Laguna Beach",
    cleanerTeam: "Ana Morales",
    subTotal: 340,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 95.31,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 4.5,
    actualHours: 4.5,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "1.5 visitas en agosto (Ana Morales). Horario: Every 3 weeks",
  }),
  // Contrato Comercial: LSG Sky Chefs (Luz and Vanessa) — 7x per week
  computeBookingFormulas({
    id: "comm-aug-lsg-sky-chefs-costa-mesa",
    date: "2026-08-31",
    clientName: "LSG Sky Chefs",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "7x per week",
    city: "Costa Mesa",
    cleanerTeam: "Luz and Vanessa",
    subTotal: 10750,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 7495,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 310,
    actualHours: 310,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "31 visitas en agosto (Luz and Vanessa). Horario: Sunday 10h; Monday 10h; Tuesday 10h; Wednesday 10h; Thursday 10h; Friday 10h; Saturday 10h",
  }),
  // Contrato Comercial: MacArthur Dental Arts (Kassandra Valentin) — 4x per week
  computeBookingFormulas({
    id: "comm-aug-macarthur-dental-arts-irvine-37",
    date: "2026-08-31",
    clientName: "MacArthur Dental Arts",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "4x per week",
    city: "Irvine",
    cleanerTeam: "Kassandra Valentin",
    subTotal: 1060,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 746.92,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 25.5,
    actualHours: 25.5,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "17 visitas en agosto (Kassandra Valentin). Horario: Monday; Tuesday; Wednesday; Thursday",
  }),
  // Contrato Comercial: Mama's Restaurant Huntington Beach (Juan Romero) — Weekly (Fri)
  computeBookingFormulas({
    id: "comm-aug-mama-s-restaurant-huntington-beach-3",
    date: "2026-08-31",
    clientName: "Mama's Restaurant Huntington Beach",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "Weekly (Fri)",
    city: "Huntington Beach",
    cleanerTeam: "Juan Romero",
    subTotal: 1898,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 902,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 16,
    actualHours: 16,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "4 visitas en agosto (Juan Romero). Horario: Friday ($200 per service flat rate)",
  }),
  // Contrato Comercial: Mama's Restaurant Los Alamitos (Juan Romero) — Weekly (Fri)
  computeBookingFormulas({
    id: "comm-aug-mama-s-restaurant-los-alamitos-4",
    date: "2026-08-31",
    clientName: "Mama's Restaurant Los Alamitos",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "Weekly (Fri)",
    city: "Los Alamitos",
    cleanerTeam: "Juan Romero",
    subTotal: 2028,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 858,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 16,
    actualHours: 16,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "4 visitas en agosto (Juan Romero). Horario: Friday ($200 per service flat rate)",
  }),
  // Contrato Comercial: Miracle Minds (Miraculous Milestones) (Luz Uribe) — 2x per week
  computeBookingFormulas({
    id: "comm-aug-miracle-minds-newport-32",
    date: "2026-08-31",
    clientName: "Miracle Minds (Miraculous Milestones)",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "2x per week",
    city: "Newport",
    cleanerTeam: "Luz Uribe",
    subTotal: 1750,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 822.25,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 22,
    actualHours: 22,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "8 visitas en agosto (Luz Uribe). Horario: Tuesday 5:30 PM; Thursday 5:30 PM",
  }),
  // Contrato Comercial: MIWA Lock CO., LTD. (Unassigned) — 1x per week
  computeBookingFormulas({
    id: "comm-aug-miwa-office-irvine-27",
    date: "2026-08-31",
    clientName: "MIWA Lock CO., LTD.",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "1x per week",
    city: "Irvine",
    cleanerTeam: "Unassigned",
    subTotal: 480,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 239,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 8,
    actualHours: 8,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "4 visitas en agosto (Unassigned). Horario: Friday 3:00 PM - 6:00 PM",
  }),
  // Contrato Comercial: MOXI3 Costa Mesa (Luz Uribe) — 3x per week
  computeBookingFormulas({
    id: "comm-aug-moxi3-costa-mesa",
    date: "2026-08-31",
    clientName: "MOXI3 Costa Mesa",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "3x per week",
    city: "Costa Mesa",
    cleanerTeam: "Luz Uribe",
    subTotal: 1100,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 642,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 49,
    actualHours: 49,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "14 visitas en agosto (Luz Uribe). Horario: Monday; Thursday; Saturday",
  }),
  // Contrato Comercial: MOXI3 Dana Point (Ana Morales) — 2x per week
  computeBookingFormulas({
    id: "comm-aug-moxi3-dana-point",
    date: "2026-08-31",
    clientName: "MOXI3 Dana Point",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "2x per week",
    city: "Dana Point",
    cleanerTeam: "Ana Morales",
    subTotal: 1000,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 642,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 27,
    actualHours: 27,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "9 visitas en agosto (Ana Morales). Horario: Monday 7:30 PM - 5:00 AM; Thursday 7:30 PM - 5:00 AM",
  }),
  // Contrato Comercial: Orange County Spine and Sports Physicians (Mirna Contreras) — 2nd & 4th Sat of Month
  computeBookingFormulas({
    id: "comm-aug-oc-spine-sports-physicians",
    date: "2026-08-31",
    clientName: "Orange County Spine and Sports Physicians",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "2nd & 4th Sat of Month",
    city: "Huntington Beach",
    cleanerTeam: "Mirna Contreras",
    subTotal: 380,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 125,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 5,
    actualHours: 5,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "2 visitas en agosto (Mirna Contreras). Horario: 2nd & 4th Sat of Month (9:00 AM - 11:20 AM)",
  }),
  // Contrato Comercial: Posh Pooch (Luz Uribe) — Every month on 2nd Mon
  computeBookingFormulas({
    id: "comm-aug-posh-pooch-seal-beach-15",
    date: "2026-08-31",
    clientName: "Posh Pooch",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "Every month on 2nd Mon",
    city: "Seal Beach",
    cleanerTeam: "Luz Uribe",
    subTotal: 338,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 92,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 4,
    actualHours: 4,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "1 visitas en agosto (Luz Uribe). Horario: Monthly (2nd Monday: Aug 10, Sep 14)",
  }),
  // Contrato Comercial: Sierra Analytical Lab (Luz Uribe) — Every 14 days
  computeBookingFormulas({
    id: "comm-aug-sierra-analytical-aliso-viejo-9",
    date: "2026-08-31",
    clientName: "Sierra Analytical Lab",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "Every 14 days",
    city: "Laguna Hills",
    cleanerTeam: "Luz Uribe",
    subTotal: 533,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 292.5,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 12,
    actualHours: 12,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "2 visitas en agosto (Luz Uribe). Horario: Every 14 days (Thursday)",
  }),
  // Contrato Comercial: Steripax (Lucia Portillo) — 5x per week
  computeBookingFormulas({
    id: "comm-aug-steripax-huntington-beach-36",
    date: "2026-08-31",
    clientName: "Steripax",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "5x per week",
    city: "Huntington Beach",
    cleanerTeam: "Lucia Portillo",
    subTotal: 5152.7,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 3386.06,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 142,
    actualHours: 142,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "21 visitas en agosto (Lucia Portillo). Horario: Monday 6:00 AM; Tuesday 6:00 AM; Wednesday 6:00 AM; Thursday 6:00 AM; Friday 6:00 AM",
  }),
  // Contrato Comercial: Swing Easy Golf Club Costa Mesa (Sandra Hernandez) — Every week on Wed
  computeBookingFormulas({
    id: "comm-aug-swing-easy-golf-club-costa-mesa-5",
    date: "2026-08-31",
    clientName: "Swing Easy Golf Club Costa Mesa",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "Every week on Wed",
    city: "Costa Mesa",
    cleanerTeam: "Sandra Hernandez",
    subTotal: 520,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 299,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 12,
    actualHours: 12,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "4 visitas en agosto (Sandra Hernandez). Horario: Wednesday (Any time)",
  }),
  // Contrato Comercial: Swing Easy Golf Club Yorba Linda (Unassigned) — Every 14 days
  computeBookingFormulas({
    id: "comm-aug-swing-easy-golf-club-yorba-linda-6",
    date: "2026-08-31",
    clientName: "Swing Easy Golf Club Yorba Linda",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "Every 14 days",
    city: "Yorba Linda",
    cleanerTeam: "Unassigned",
    subTotal: 486,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 200,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 6,
    actualHours: 6,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "2 visitas en agosto (Unassigned). Horario: Every 14 days (Thursday)",
  }),
  // Contrato Comercial: The Harper Wedding Venue (Juan Romero) — As needed (Events)
  computeBookingFormulas({
    id: "comm-aug-the-harper-wedding-venue-costa-mesa-33",
    date: "2026-08-31",
    clientName: "The Harper Wedding Venue",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "As needed (Events)",
    city: "Costa Mesa",
    cleanerTeam: "Juan Romero",
    subTotal: 2990,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 1170,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 65,
    actualHours: 65,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "13 visitas en agosto (Juan Romero). Horario: 13 eventos en agosto ($90 por evento a Juan Romero | Turno 12 AM - 7 AM)",
  }),
  // Contrato Comercial: University Park Dental (Unassigned) — Every 14 days (Mon)
  computeBookingFormulas({
    id: "comm-aug-university-park-dental-irvine-10",
    date: "2026-08-31",
    clientName: "University Park Dental",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "Every 14 days (Mon)",
    city: "Irvine",
    cleanerTeam: "Unassigned",
    subTotal: 325,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 112.13,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 5,
    actualHours: 5,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "2 visitas en agosto (Unassigned). Horario: Every 14 days (Monday 9:30 AM - 12:00 PM)",
  }),
  // Contrato Comercial: VNTR Fitness (Ana Morales) — 3x per week
  computeBookingFormulas({
    id: "comm-aug-vntr-fitness-rancho-santa-margarita-26",
    date: "2026-08-31",
    clientName: "VNTR Fitness",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "3x per week",
    city: "Rancho Santa Margarita",
    cleanerTeam: "Ana Morales",
    subTotal: 1258,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 858,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 32.5,
    actualHours: 32.5,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "13 visitas en agosto (Ana Morales). Horario: Monday 8:00 PM - 11:00 PM; Wednesday 8:00 PM - 11:00 PM; Friday 8:00 PM - 11:00 PM",
  }),
  // Contrato Comercial: Wren Spa (Luz Uribe) — 1x per week
  computeBookingFormulas({
    id: "comm-aug-wren-spa-costa-mesa-34",
    date: "2026-08-31",
    clientName: "Wren Spa",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "1x per week",
    city: "Costa Mesa",
    cleanerTeam: "Luz Uribe",
    subTotal: 740,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 399,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 16,
    actualHours: 16,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "4 visitas en agosto (Luz Uribe). Horario: Thursday 6:00 AM - 11:30 AM (Finish by 8:30 AM)",
  }),
  // Contrato Comercial: Lifted Dentistry (Unassigned) — Every 14 days
  computeBookingFormulas({
    id: "comm-aug-lifted-dentistry-irvine",
    date: "2026-08-31",
    clientName: "Lifted Dentistry",
    service: "Commercial Cleaning",
    serviceCategory: "Commercial Cleaning",
    frequency: "Every 14 days",
    city: "Irvine",
    cleanerTeam: "Unassigned",
    subTotal: 335,
    salesTax: 0,
    processingFee: 0,
    tip: 0,
    teamEarningsWithoutTips: 149,
    merchantFee: 0,
    stripeFee: 0,
    durationHours: 6,
    actualHours: 6,
    bookedBy: "Commercial Contract",
    status: "completed",
    notes: "2 visitas en agosto (Unassigned). Horario: Every 14 days (Thursday)",
  }),
];

export const augustSalesTrackerBookings: ServiceBookingRow[] = [
  ...augustResidentialBookings,
  ...augustCommercialBookings,
];
